/* tslint:disable */
/* eslint-disable */
export * from './shared/accountmappingoption';
export * from './shared/accountstatus';
export * from './shared/address';
export * from './shared/addresstype';
export * from './shared/attachment';
export * from './shared/bankaccount';
export * from './shared/bankaccountmappingoption';
export * from './shared/bankaccountprototype';
export * from './shared/bankaccountstatus';
export * from './shared/bankaccounttype';
export * from './shared/bill';
export * from './shared/billaccountref';
export * from './BillEventPayload';
export * from './BillEventWebhook';
export * from './shared/billlineitem';
export * from './shared/billmappingoptions';
export * from './shared/billpayment';
export * from './shared/billpaymentaccountref';
export * from './shared/billpaymentprototype';
export * from './shared/billprototype';
export * from './shared/billstatus';
export * from './shared/billtaxrateref';
export * from './shared/bills';
export * from './shared/clientratelimitwebhook';
export * from './shared/clientratelimitwebhookpayload';
export * from './shared/companies';
export * from './shared/company';
export * from './CompanyDetails';
export * from './shared/companyinformation';
export * from './shared/companyreference';
export * from './shared/companyreferencelinks';
export * from './shared/companyrequestbody';
export * from './shared/companyupdaterequest';
export * from './shared/connection';
export * from './shared/connections';
export * from './operations/createconnectionrequestbody';
export * from './shared/dataconnectionerror';
export * from './shared/dataconnectionstatus';
export * from './DataStatus';
export * from './ErrorMessage';
export * from './shared/errorvalidation';
export * from './shared/errorvalidationitem';
export * from './shared/halref';
export * from './shared/links';
export * from './shared/pagination';
export * from './PagingInfo';
export * from './shared/paymentmappingoptions';
export * from './PullOperation';
export * from './PullOperations';
export * from './PushChangeType';
export * from './PushOperation';
export * from './PushOperationChange';
export * from './PushOperationRef';
export * from './PushOperationStatus';
export * from './PushOperations';
export * from './SourceModifiedDate';
export * from './Status';
export * from './shared/supplier';
export * from './shared/supplierprototype';
export * from './shared/supplierref';
export * from './shared/supplierstatus';
export * from './shared/suppliers';
export * from './shared/taxratemappingoption';
export * from './shared/trackingref';
export * from './UpdateConnection';
export * from './Validation';
export * from './ValidationItem';
export * from './shared/codatfile';
export * from './shared/attachmentupload';
export * from './_speakeasy_enums';
export * from './_speakeasy_hoisted';
export type { Security } from '../../lib/sdkconfig';

export type { ListCompaniesRequest } from './operations/listcompanies';
export type { GetCompanyRequest } from './operations/getcompany';
export type { ReplaceCompanyRequest } from './operations/replacecompany';
export type { UpdateCompanyRequest } from './operations/updatecompany';
export type { DeleteCompanyRequest } from './operations/deletecompany';
export type { ListConnectionsRequest } from './operations/listconnections';
export type { CreateConnectionRequest } from './operations/createconnection';
export type { GetConnectionRequest } from './operations/getconnection';
export type { UnlinkConnectionRequest } from './operations/unlinkconnection';
export type { DeleteConnectionRequest } from './operations/deleteconnection';
export type { GetCompanyInformationRequest } from './operations/getcompanyinformation';
export type { GetMappingOptionsBillsRequest } from './operations/getmappingoptionsbills';
export type { GetMappingOptionsPaymentsRequest } from './operations/getmappingoptionspayments';
export type { ListBillsRequest } from './operations/listbills';
export type { CreateBillRequest } from './operations/createbill';
export type { UpdateBillRequest } from './operations/updatebill';
export type { ListBillAttachmentsRequest } from './operations/listbillattachments';
export type { UploadBillAttachmentRequest } from './operations/uploadbillattachment';
export type { DownloadBillAttachmentRequest } from './operations/downloadbillattachment';
export type { CreateBillPaymentRequest } from './operations/createbillpayment';
export type { ListSuppliersRequest } from './operations/listsuppliers';
export type { CreateSupplierRequest } from './operations/createsupplier';
export type { UpdateSupplierRequest } from './operations/updatesupplier';
export type { CreateBankAccountRequest } from './operations/createbankaccount';

export * as operations from './operations';
export * as shared from './shared';
