/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Code to identify the underlying transaction.
 */
export enum TransactionCode {
  Unknown = "Unknown",
  Fee = "Fee",
  Payment = "Payment",
  Cash = "Cash",
  Transfer = "Transfer",
  Interest = "Interest",
  Cashback = "Cashback",
  Cheque = "Cheque",
  DirectDebit = "DirectDebit",
  Purchase = "Purchase",
  StandingOrder = "StandingOrder",
  Adjustment = "Adjustment",
  Credit = "Credit",
  Other = "Other",
  NotSupported = "NotSupported",
}
