/* tslint:disable */
/* eslint-disable */
export * from './AccessToken';
export * from './shared/apikeydetails';
export * from './shared/apikeys';
export * from './shared/branding';
export * from './shared/brandingbutton';
export * from './shared/brandingimage';
export * from './shared/brandinglogo';
export * from './shared/clientratelimitwebhook';
export * from './shared/clientratelimitwebhookpayload';
export * from './shared/companies';
export * from './shared/company';
export * from './shared/companyaccesstoken';
export * from './shared/companydetails';
export * from './CompanyProductWebhook';
export * from './CompanyProductWebhookPayload';
export * from './shared/companyreference';
export * from './shared/companyreferencelinks';
export * from './shared/companyrequestbody';
export * from './shared/companysyncsettings';
export * from './shared/companyupdaterequest';
export * from './shared/companywebhook';
export * from './shared/connection';
export * from './shared/connectionmanagementaccesstoken';
export * from './shared/connectionmanagementallowedorigins';
export * from './shared/connectionwebhook';
export * from './shared/connectionwebhookpayload';
export * from './shared/connections';
export * from './shared/createapikey';
export * from './operations/createconnectionrequestbody';
export * from './shared/customdatatypeconfiguration';
export * from './shared/customdatatyperecord';
export * from './shared/customdatatyperecords';
export * from './shared/dataconnectionerror';
export * from './shared/dataconnectionstatus';
export * from './shared/datastatus';
export * from './shared/datastatuses';
export * from './DataType';
export * from './shared/datatypefeature';
export * from './shared/datatypereadsummary';
export * from './shared/datatypewritewebhook';
export * from './shared/datatypewritewebhookpayload';
export * from './shared/datatypewritewebhookrecord';
export * from './ErrorMessage';
export * from './shared/errorvalidation';
export * from './shared/errorvalidationitem';
export * from './shared/featurestate';
export * from './shared/featuretype';
export * from './shared/halref';
export * from './shared/imagereference';
export * from './shared/integration';
export * from './shared/integrations';
export * from './shared/issue';
export * from './shared/issuelinks';
export * from './shared/links';
export * from './shared/modifieddate';
export * from './PagingInfo';
export * from './shared/profile';
export * from './shared/pulloperation';
export * from './shared/pulloperations';
export * from './shared/pushchangetype';
export * from './shared/pushfieldvalidation';
export * from './shared/pushoperation';
export * from './shared/pushoperationchange';
export * from './shared/pushoperationref';
export * from './shared/pushoperationstatus';
export * from './shared/pushoperations';
export * from './shared/pushoption';
export * from './shared/pushoptionchoice';
export * from './shared/pushoptionproperty';
export * from './shared/pushoptiontype';
export * from './shared/pushvalidationinfo';
export * from './shared/readcompletedwebhook';
export * from './shared/readcompletedwebhookpayload';
export * from './operations/refreshproductdatarequestbody';
export * from './operations/setcompanysyncsettingsrequestbody';
export * from './shared/sourcetype';
export * from './shared/status';
export * from './shared/supplementaldataconfiguration';
export * from './shared/supplementaldatasourceconfiguration';
export * from './shared/supportedfeature';
export * from './shared/syncsetting';
export * from './shared/syncsettings';
export * from './shared/updateconnectionstatus';
export * from './operations/updateprofilesyncsettings';
export * from './shared/validation';
export * from './shared/validationitem';
export * from './shared/validationitem1';
export * from './shared/validationresult';
export * from './shared/webhookconsumer';
export * from './shared/webhookconsumerprototype';
export * from './shared/webhookconsumers';
export * from './WebhookZapierKey';
export * from './shared/writestatus';
export * from './shared/writetype';
export * from './_speakeasy_enums';
export * from './_speakeasy_hoisted';
export type { Security } from '../../lib/sdkconfig';

export type { ListCompaniesRequest } from './operations/listcompanies';
export type { GetCompanyRequest } from './operations/getcompany';
export type { ReplaceCompanyRequest } from './operations/replacecompany';
export type { UpdateCompanyRequest } from './operations/updatecompany';
export type { DeleteCompanyRequest } from './operations/deletecompany';
export type { AddProductRequest } from './operations/addproduct';
export type { RemoveProductRequest } from './operations/removeproduct';
export type { RefreshProductDataRequest } from './operations/refreshproductdata';
export type { ListConnectionsRequest } from './operations/listconnections';
export type { CreateConnectionRequest } from './operations/createconnection';
export type { GetConnectionRequest } from './operations/getconnection';
export type { UnlinkConnectionRequest } from './operations/unlinkconnection';
export type { DeleteConnectionRequest } from './operations/deleteconnection';
export type { UpdateConnectionAuthorizationRequest } from './operations/updateconnectionauthorization';
export type { GetCompanyAccessTokenRequest } from './operations/getcompanyaccesstoken';
export type { GetCompanySyncSettingsRequest } from './operations/getcompanysyncsettings';
export type { SetCompanySyncSettingsRequest } from './operations/setcompanysyncsettings';
export type { GetConnectionManagementAccessTokenRequest } from './operations/getconnectionmanagementaccesstoken';
export type { RefreshCompanyDataRequest } from './operations/refreshcompanydata';
export type { RefreshDataTypeRequest } from './operations/refreshdatatype';
export type { GetCompanyDataStatusRequest } from './operations/getcompanydatastatus';
export type { ListPullOperationsRequest } from './operations/listpulloperations';
export type { GetPullOperationRequest } from './operations/getpulloperation';
export type { DeleteWebhookConsumerRequest } from './operations/deletewebhookconsumer';
export type { ListIntegrationsRequest } from './operations/listintegrations';
export type { GetIntegrationRequest } from './operations/getintegration';
export type { GetIntegrationsBrandingRequest } from './operations/getintegrationsbranding';
export type { DeleteApiKeyRequest } from './operations/deleteapikey';
export type { GetReadValidationResultsRequest } from './operations/getreadvalidationresults';
export type { GetCreateUpdateModelOptionsByDataTypeRequest } from './operations/getcreateupdatemodeloptionsbydatatype';
export type { GetCompanyPushHistoryRequest } from './operations/getcompanypushhistory';
export type { GetPushOperationRequest } from './operations/getpushoperation';
export type { GetSupplementalDataConfigurationRequest } from './operations/getsupplementaldataconfiguration';
export type { ConfigureSupplementalDataRequest } from './operations/configuresupplementaldata';
export type { GetCustomDataTypeConfigurationRequest } from './operations/getcustomdatatypeconfiguration';
export type { ConfigureCustomDataTypeRequest } from './operations/configurecustomdatatype';
export type { RefreshCustomDataTypeRequest } from './operations/refreshcustomdatatype';
export type { ListCustomDataTypeRecordsRequest } from './operations/listcustomdatatyperecords';

export * as operations from './operations';
export * as shared from './shared';
