/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ListConnectionsRequest = {
  /**
   * Unique identifier for a company.
   */
  companyId: string;
  /**
   * Page number. [Read more](https://docs.codat.io/using-the-api/paging).
   */
  page?: number | undefined;
  /**
   * Number of records to return in a page. [Read more](https://docs.codat.io/using-the-api/paging).
   */
  pageSize?: number | undefined;
  /**
   * Codat query string. [Read more](https://docs.codat.io/using-the-api/querying).
   */
  query?: string | undefined;
  /**
   * Field to order results by. [Read more](https://docs.codat.io/using-the-api/ordering-results).
   */
  orderBy?: string | undefined;
};

/** @internal */
export const ListConnectionsRequest$inboundSchema: z.ZodType<
  ListConnectionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  companyId: z.string(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
  query: z.string().optional(),
  orderBy: z.string().optional(),
});

/** @internal */
export type ListConnectionsRequest$Outbound = {
  companyId: string;
  page: number;
  pageSize: number;
  query?: string | undefined;
  orderBy?: string | undefined;
};

/** @internal */
export const ListConnectionsRequest$outboundSchema: z.ZodType<
  ListConnectionsRequest$Outbound,
  z.ZodTypeDef,
  ListConnectionsRequest
> = z.object({
  companyId: z.string(),
  page: z.number().int().default(1),
  pageSize: z.number().int().default(100),
  query: z.string().optional(),
  orderBy: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ListConnectionsRequest$ {
  /** @deprecated use `ListConnectionsRequest$inboundSchema` instead. */
  export const inboundSchema = ListConnectionsRequest$inboundSchema;
  /** @deprecated use `ListConnectionsRequest$outboundSchema` instead. */
  export const outboundSchema = ListConnectionsRequest$outboundSchema;
  /** @deprecated use `ListConnectionsRequest$Outbound` instead. */
  export type Outbound = ListConnectionsRequest$Outbound;
}

export function listConnectionsRequestToJSON(
  listConnectionsRequest: ListConnectionsRequest,
): string {
  return JSON.stringify(
    ListConnectionsRequest$outboundSchema.parse(listConnectionsRequest),
  );
}

export function listConnectionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListConnectionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListConnectionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListConnectionsRequest' from JSON`,
  );
}
