/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAccountingJournalRequest = {
  /**
   * Unique identifier for a company.
   */
  companyId: string;
  /**
   * Unique identifier for a journal.
   */
  journalId: string;
};

/** @internal */
export const GetAccountingJournalRequest$inboundSchema: z.ZodType<
  GetAccountingJournalRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  companyId: z.string(),
  journalId: z.string(),
});
/** @internal */
export type GetAccountingJournalRequest$Outbound = {
  companyId: string;
  journalId: string;
};

/** @internal */
export const GetAccountingJournalRequest$outboundSchema: z.ZodType<
  GetAccountingJournalRequest$Outbound,
  z.ZodTypeDef,
  GetAccountingJournalRequest
> = z.object({
  companyId: z.string(),
  journalId: z.string(),
});

export function getAccountingJournalRequestToJSON(
  getAccountingJournalRequest: GetAccountingJournalRequest,
): string {
  return JSON.stringify(
    GetAccountingJournalRequest$outboundSchema.parse(
      getAccountingJournalRequest,
    ),
  );
}
export function getAccountingJournalRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountingJournalRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountingJournalRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountingJournalRequest' from JSON`,
  );
}
