/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetCreatePaymentModelRequest = {
  /**
   * Unique identifier for a company.
   */
  companyId: string;
  /**
   * Unique identifier for a connection.
   */
  connectionId: string;
};

/** @internal */
export type GetCreatePaymentModelRequest$Outbound = {
  companyId: string;
  connectionId: string;
};

/** @internal */
export const GetCreatePaymentModelRequest$outboundSchema: z.ZodType<
  GetCreatePaymentModelRequest$Outbound,
  z.ZodTypeDef,
  GetCreatePaymentModelRequest
> = z.object({
  companyId: z.string(),
  connectionId: z.string(),
});

export function getCreatePaymentModelRequestToJSON(
  getCreatePaymentModelRequest: GetCreatePaymentModelRequest,
): string {
  return JSON.stringify(
    GetCreatePaymentModelRequest$outboundSchema.parse(
      getCreatePaymentModelRequest,
    ),
  );
}
