/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Name of underlying data type.
 */
export const AccountTransactionLineRecordRefDataType = {
  BankTransactions: "bankTransactions",
  BillCreditNotes: "billCreditNotes",
  BillPayments: "billPayments",
  Bills: "bills",
  CreditNotes: "creditNotes",
  DirectCosts: "directCosts",
  DirectIncomes: "directIncomes",
  Invoices: "invoices",
  JournalEntries: "journalEntries",
  Payments: "payments",
  Transfers: "transfers",
} as const;
/**
 * Name of underlying data type.
 */
export type AccountTransactionLineRecordRefDataType = ClosedEnum<
  typeof AccountTransactionLineRecordRefDataType
>;

/**
 * Links an account transaction line to the underlying record that created it.
 */
export type AccountTransactionLineRecordRef = {
  /**
   * 'id' of the underlying record or data type.
   */
  id?: string | undefined;
  /**
   * Name of underlying data type.
   */
  dataType?: AccountTransactionLineRecordRefDataType | undefined;
};

/** @internal */
export const AccountTransactionLineRecordRefDataType$inboundSchema:
  z.ZodNativeEnum<typeof AccountTransactionLineRecordRefDataType> = z
    .nativeEnum(AccountTransactionLineRecordRefDataType);
/** @internal */
export const AccountTransactionLineRecordRefDataType$outboundSchema:
  z.ZodNativeEnum<typeof AccountTransactionLineRecordRefDataType> =
    AccountTransactionLineRecordRefDataType$inboundSchema;

/** @internal */
export const AccountTransactionLineRecordRef$inboundSchema: z.ZodType<
  AccountTransactionLineRecordRef,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  dataType: AccountTransactionLineRecordRefDataType$inboundSchema.optional(),
});
/** @internal */
export type AccountTransactionLineRecordRef$Outbound = {
  id?: string | undefined;
  dataType?: string | undefined;
};

/** @internal */
export const AccountTransactionLineRecordRef$outboundSchema: z.ZodType<
  AccountTransactionLineRecordRef$Outbound,
  z.ZodTypeDef,
  AccountTransactionLineRecordRef
> = z.object({
  id: z.string().optional(),
  dataType: AccountTransactionLineRecordRefDataType$outboundSchema.optional(),
});

export function accountTransactionLineRecordRefToJSON(
  accountTransactionLineRecordRef: AccountTransactionLineRecordRef,
): string {
  return JSON.stringify(
    AccountTransactionLineRecordRef$outboundSchema.parse(
      accountTransactionLineRecordRef,
    ),
  );
}
export function accountTransactionLineRecordRefFromJSON(
  jsonString: string,
): SafeParseResult<AccountTransactionLineRecordRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AccountTransactionLineRecordRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AccountTransactionLineRecordRef' from JSON`,
  );
}
