/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

/**
 * The status of the product variant.
 */
export const ProductVariantStatus = {
  Unknown: "Unknown",
  Published: "Published",
  Unpublished: "Unpublished",
} as const;
/**
 * The status of the product variant.
 */
export type ProductVariantStatus = ClosedEnum<typeof ProductVariantStatus>;

/** @internal */
export const ProductVariantStatus$inboundSchema: z.ZodNativeEnum<
  typeof ProductVariantStatus
> = z.nativeEnum(ProductVariantStatus);

/** @internal */
export const ProductVariantStatus$outboundSchema: z.ZodNativeEnum<
  typeof ProductVariantStatus
> = ProductVariantStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProductVariantStatus$ {
  /** @deprecated use `ProductVariantStatus$inboundSchema` instead. */
  export const inboundSchema = ProductVariantStatus$inboundSchema;
  /** @deprecated use `ProductVariantStatus$outboundSchema` instead. */
  export const outboundSchema = ProductVariantStatus$outboundSchema;
}
