/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Company, Company$ } from "./company";
import { ErrorMessage, ErrorMessage$ } from "./errormessage";
import * as z from "zod";

export type CreateCompanyResponse = ErrorMessage | Company;

/** @internal */
export namespace CreateCompanyResponse$ {
    export const inboundSchema: z.ZodType<CreateCompanyResponse, z.ZodTypeDef, unknown> = z.union([
        ErrorMessage$.inboundSchema,
        Company$.inboundSchema,
    ]);

    export type Outbound = ErrorMessage$.Outbound | Company$.Outbound;
    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateCompanyResponse> = z.union(
        [ErrorMessage$.outboundSchema, Company$.outboundSchema]
    );
}
