/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetPullOperationRequest = {
    /**
     * Unique identifier for a company.
     */
    companyId: string;
    /**
     * Unique identifier for the dataset that completed its sync.
     */
    datasetId: string;
};

/** @internal */
export namespace GetPullOperationRequest$ {
    export const inboundSchema: z.ZodType<GetPullOperationRequest, z.ZodTypeDef, unknown> =
        z.object({
            companyId: z.string(),
            datasetId: z.string(),
        });

    export type Outbound = {
        companyId: string;
        datasetId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetPullOperationRequest> =
        z.object({
            companyId: z.string(),
            datasetId: z.string(),
        });
}
