/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type HalRef = {
    /**
     * Uri hypertext reference.
     */
    href?: string | undefined;
};

/** @internal */
export namespace HalRef$ {
    export const inboundSchema: z.ZodType<HalRef, z.ZodTypeDef, unknown> = z.object({
        href: z.string().optional(),
    });

    export type Outbound = {
        href?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, HalRef> = z.object({
        href: z.string().optional(),
    });
}
