/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Image reference.
 */
export type ImageReference = {
    /**
     * Source URL for image.
     */
    src?: string | undefined;
    /**
     * Alternative text when image is not available.
     */
    alt?: string | undefined;
};

/** @internal */
export namespace ImageReference$ {
    export const inboundSchema: z.ZodType<ImageReference, z.ZodTypeDef, unknown> = z.object({
        src: z.string().optional(),
        alt: z.string().optional(),
    });

    export type Outbound = {
        src?: string | undefined;
        alt?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ImageReference> = z.object({
        src: z.string().optional(),
        alt: z.string().optional(),
    });
}
