/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SyncSetting, SyncSetting$ } from "./syncsetting";
import * as z from "zod";

export type SyncSettings = {
    /**
     * Unique identifier for your client in Codat.
     */
    clientId?: string | undefined;
    /**
     * Set to `True` if you want to override the default [sync settings](https://docs.codat.io/knowledge-base/advanced-sync-settings).
     */
    overridesDefaults?: boolean | undefined;
    settings?: Array<SyncSetting> | undefined;
};

/** @internal */
export namespace SyncSettings$ {
    export const inboundSchema: z.ZodType<SyncSettings, z.ZodTypeDef, unknown> = z
        .object({
            clientId: z.string().optional(),
            overridesDefaults: z.boolean().optional(),
            settings: z.array(SyncSetting$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.clientId === undefined ? null : { clientId: v.clientId }),
                ...(v.overridesDefaults === undefined
                    ? null
                    : { overridesDefaults: v.overridesDefaults }),
                ...(v.settings === undefined ? null : { settings: v.settings }),
            };
        });

    export type Outbound = {
        clientId?: string | undefined;
        overridesDefaults?: boolean | undefined;
        settings?: Array<SyncSetting$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, SyncSettings> = z
        .object({
            clientId: z.string().optional(),
            overridesDefaults: z.boolean().optional(),
            settings: z.array(SyncSetting$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                ...(v.clientId === undefined ? null : { clientId: v.clientId }),
                ...(v.overridesDefaults === undefined
                    ? null
                    : { overridesDefaults: v.overridesDefaults }),
                ...(v.settings === undefined ? null : { settings: v.settings }),
            };
        });
}
