/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { companyInfoGetAccountingProfile } from "../../funcs/companyInfoGetAccountingProfile.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetAccountingProfileRequest$inboundSchema,
};

export const tool$companyInfoGetAccountingProfile: ToolDefinition<typeof args> =
  {
    name: "company-info-get-accounting-profile",
    description: `Get company accounting profile

Gets the latest basic info for a company.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await companyInfoGetAccountingProfile(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
