/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { connectionsCreate } from "../../funcs/connectionsCreate.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateConnectionRequest$inboundSchema,
};

export const tool$connectionsCreate: ToolDefinition<typeof args> = {
  name: "connections-create",
  description: `Create connection

Creates a connection for the company by providing a valid \`platformKey\`. 

Use the [List Integrations](https://docs.codat.io/platform-api#/operations/list-integrations) endpoint to access valid platform keys. `,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await connectionsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
