/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { manageDataRefreshDataType } from "../../funcs/manageDataRefreshDataType.js";
import * as operations from "../../sdk/models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.RefreshDataTypeRequest$inboundSchema,
};

export const tool$manageDataRefreshDataType: ToolDefinition<typeof args> = {
  name: "manage-data-refresh-data-type",
  description: `Refresh data type

Refreshes a given data type for a given company.

This is an asynchronous operation, and will bring updated data into Codat from the linked integration for you to view.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await manageDataRefreshDataType(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
