/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DownloadBillAttachmentRequest = {
  /**
   * Unique identifier for a company.
   */
  companyId: string;
  /**
   * Unique identifier for a connection.
   */
  connectionId: string;
  /**
   * Unique identifier for a bill.
   */
  billId: string;
  /**
   * Unique identifier for an attachment.
   */
  attachmentId: string;
};

/** @internal */
export const DownloadBillAttachmentRequest$inboundSchema: z.ZodType<
  DownloadBillAttachmentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  companyId: z.string(),
  connectionId: z.string(),
  billId: z.string(),
  attachmentId: z.string(),
});

/** @internal */
export type DownloadBillAttachmentRequest$Outbound = {
  companyId: string;
  connectionId: string;
  billId: string;
  attachmentId: string;
};

/** @internal */
export const DownloadBillAttachmentRequest$outboundSchema: z.ZodType<
  DownloadBillAttachmentRequest$Outbound,
  z.ZodTypeDef,
  DownloadBillAttachmentRequest
> = z.object({
  companyId: z.string(),
  connectionId: z.string(),
  billId: z.string(),
  attachmentId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DownloadBillAttachmentRequest$ {
  /** @deprecated use `DownloadBillAttachmentRequest$inboundSchema` instead. */
  export const inboundSchema = DownloadBillAttachmentRequest$inboundSchema;
  /** @deprecated use `DownloadBillAttachmentRequest$outboundSchema` instead. */
  export const outboundSchema = DownloadBillAttachmentRequest$outboundSchema;
  /** @deprecated use `DownloadBillAttachmentRequest$Outbound` instead. */
  export type Outbound = DownloadBillAttachmentRequest$Outbound;
}
