/* tslint:disable */
/* eslint-disable */
/**
 * Expenses
 * The API for Codat\'s Expenses solution.  Expenses is an API and a set of supporting tools. It has been built to enable corporate card and expense management platforms to provide high-quality integrations with multiple accounting software through a standardized API.  [Explore solution](https://docs.codat.io/sync-for-expenses/overview) | [See our OpenAPI spec](https://github.com/codatio/oas)  Not seeing the endpoints you\'re expecting? We\'ve [reorganized our solutions](https://docs.codat.io/updates/230901-new-products), and you may be using a [different version of Expenses](https://docs.codat.io/sync-for-expenses-v1-api#/).  --- <!-- Start Codat Tags Table --> ## Endpoints  | Endpoints | Description | | :- |:- | | Companies | Create and manage your SMB users\' companies. | | Connections | Create new and manage existing data connections for a company. | | Configuration | View and manage mapping configuration and defaults for expense transactions. | | Sync | Monitor the status of data syncs. | | Expenses | Create and update transactions that represent your customers\' spend. | | Transfers | Create and update transactions that represent the movement of your customers\' money. | | Reimbursements | Create and update transactions that represent your customers\' repayable spend. | | Attachments | Attach receipts to a transaction for a complete audit trail. | | Transaction status | Monitor the status of individual transactions in data syncs. | | Manage data | Control and monitor the retrieval of data from an integration. | | Push operations | View historic push operations. | | Accounts | Create accounts and view account schemas. | | Customers | Get, create, and update customers. | | Suppliers | Get, create, and update suppliers. | <!-- End Codat Tags Table -->
 *
 * The version of the OpenAPI document: prealpha
 * Contact: expenses@codat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../../runtime';
/**
 * Reference of the account you are transferring money from.
 * @export
 * @interface AccountReference
 */
export interface AccountReference {
    /**
     * 'id' from the Accounts data type.
     * @type {string}
     * @memberof AccountReference
     */
    id: string;
}

/**
 * Check if a given object implements the AccountReference interface.
 */
export function instanceOfAccountReference(value: object): value is AccountReference {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function AccountReferenceFromJSON(json: any): AccountReference {
    return AccountReferenceFromJSONTyped(json, false);
}

export function AccountReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountReference {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function AccountReferenceToJSON(json: any): AccountReference {
    return AccountReferenceToJSONTyped(json, false);
}

export function AccountReferenceToJSONTyped(value?: AccountReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}


export interface TransferAccountReference {
    /**
     * 'id' from the Accounts data type.
     * @type {string}
     * @memberof AccountReference
     */
    id: string;
}

export interface TransferTransactionRequestAccountReference {
    /**
     * 'id' from the Accounts data type.
     * @type {string}
     * @memberof AccountReference
     */
    id: string;
}
