/* tslint:disable */
/* eslint-disable */
/**
 * Expenses
 * The API for Codat\'s Expenses solution.  Expenses is an API and a set of supporting tools. It has been built to enable corporate card and expense management platforms to provide high-quality integrations with multiple accounting software through a standardized API.  [Explore solution](https://docs.codat.io/sync-for-expenses/overview) | [See our OpenAPI spec](https://github.com/codatio/oas)  Not seeing the endpoints you\'re expecting? We\'ve [reorganized our solutions](https://docs.codat.io/updates/230901-new-products), and you may be using a [different version of Expenses](https://docs.codat.io/sync-for-expenses-v1-api#/).  --- <!-- Start Codat Tags Table --> ## Endpoints  | Endpoints | Description | | :- |:- | | Companies | Create and manage your SMB users\' companies. | | Connections | Create new and manage existing data connections for a company. | | Configuration | View and manage mapping configuration and defaults for expense transactions. | | Sync | Monitor the status of data syncs. | | Expenses | Create and update transactions that represent your customers\' spend. | | Transfers | Create and update transactions that represent the movement of your customers\' money. | | Reimbursements | Create and update transactions that represent your customers\' repayable spend. | | Attachments | Attach receipts to a transaction for a complete audit trail. | | Transaction status | Monitor the status of individual transactions in data syncs. | | Manage data | Control and monitor the retrieval of data from an integration. | | Push operations | View historic push operations. | | Accounts | Create accounts and view account schemas. | | Customers | Get, create, and update customers. | | Suppliers | Get, create, and update suppliers. | <!-- End Codat Tags Table -->
 *
 * The version of the OpenAPI document: prealpha
 * Contact: expenses@codat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateBankAccountResponseBankAccountType } from '../_speakeasy_enums';
import type { BankAccountType } from '../_speakeasy_enums';
import { mapValues } from '../../../runtime';
import { Decimal, toDecimal, fromDecimal } from '../../../runtime';
import type { SupplementalData } from './supplementaldata';
import {
    SupplementalDataFromJSON,
    SupplementalDataFromJSONTyped,
    SupplementalDataToJSON,
    SupplementalDataToJSONTyped,
} from './supplementaldata';
import type { Metadata } from './metadata';
import {
    MetadataFromJSON,
    MetadataFromJSONTyped,
    MetadataToJSON,
    MetadataToJSONTyped,
} from './metadata';
import type { BankAccountStatus } from './bankaccountstatus';
import {
    BankAccountStatusFromJSON,
    BankAccountStatusFromJSONTyped,
    BankAccountStatusToJSON,
    BankAccountStatusToJSONTyped,
} from './bankaccountstatus';

/**
 * > **Accessing Bank Accounts through Banking API**
 * > 
 * > This datatype was originally used for accessing bank account data both in accounting integrations and open banking aggregators. 
 * > 
 * > To view bank account data through the Banking API, please refer to the new [Banking: Account](https://docs.codat.io/sync-for-expenses-api#/schemas/Account) data type.
 * 
 * ## Overview
 * 
 * A list of bank accounts associated with a company and a specific data connection.
 * 
 * Bank accounts data includes:
 * * The name and ID of the account in the accounting software.
 * * The currency and balance of the account.
 * * The sort code and account number.
 * @export
 * @interface BankAccount
 */
export interface BankAccount {
    /**
     * Name of the bank account in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    accountName?: string | null;
    /**
     * The type of transactions and balances on the account.  
     * For Credit accounts, positive balances are liabilities, and positive transactions **reduce** liabilities.  
     * For Debit accounts, positive balances are assets, and positive transactions **increase** assets.
     * @type {string}
     * @memberof BankAccount
     */
    accountType?: BankAccountType;
    /**
     * Code used to identify each nominal account for a business.
     * @type {string}
     * @memberof BankAccount
     */
    nominalCode?: string | null;
    /**
     * Sort code for the bank account.
     * 
     * Xero integrations
     * The sort code is only displayed when the currency = GBP and the sort code and account number sum to 14 digits. For non-GBP accounts, this field is not populated.
     * @type {string}
     * @memberof BankAccount
     */
    sortCode?: string | null;
    /**
     * Account number for the bank account.
     * 
     * Xero integrations
     * Only a UK account number shows for bank accounts with GBP currency and a combined total of sort code and account number that equals 14 digits, For non-GBP accounts, the full bank account number is populated.
     * 
     * FreeAgent integrations
     * For Credit accounts, only the last four digits are required. For other types, the field is optional.
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber?: string | null;
    /**
     * International bank account number of the account. Often used when making or receiving international payments.
     * @type {string}
     * @memberof BankAccount
     */
    iBan?: string | null;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     * 
     * ## Unknown currencies
     * 
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction. 
     * 
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     * @type {string}
     * @memberof BankAccount
     */
    currency?: string;
    /**
     * Balance of the bank account.
     * @type {number}
     * @memberof BankAccount
     */
    balance?: Decimal | number | null;
    /**
     * The institution of the bank account.
     * @type {string}
     * @memberof BankAccount
     */
    institution?: string | null;
    /**
     * Total available balance of the bank account as reported by the underlying data source. This may take into account overdrafts or pending transactions for example.
     * @type {number}
     * @memberof BankAccount
     */
    availableBalance?: Decimal | number | null;
    /**
     * Pre-arranged overdraft limit of the account.
     * 
     * The value is always positive. For example, an overdraftLimit of `1000` means that the balance of the account can go down to `-1000`.
     * @type {number}
     * @memberof BankAccount
     */
    overdraftLimit?: Decimal | number | null;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof BankAccount
     */
    status?: BankAccountStatus;
    /**
     * The date when the record was last fetched from the accounting software, commerce software, or open banking provider and updated in Codat’s data cache.
     * 
     * Use it to identify and retrieve records that have changed since your last fetch. For example, filtering `modifiedDate` to today will provide new records updated in Codat today.
     * 
     * This date is populated for all data types except for attachments, balance sheets, company information, and profit & loss reports ([read more](https://docs.codat.io/using-the-api/modified-dates#modified-date)).
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    modifiedDate?: string;
    /**
     * The date when a record was last modified in the accounting software, usually by the business or a business process. For example, when payments are made against an invoice. 
     * 
     * It is not populated ([read more](https://docs.codat.io/using-the-api/modified-dates#source-modified-date)) when:
     *   - Pulling attachments
     *   - The accounting software does not provide modification dates for a data type
     *   - A record has been deleted from the source platform and Codat doesn't have a record of when the deletion occurred
     *   - A record has been voided. For certain platforms that soft delete records, `isDeleted` metadata is used to identify void records
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    sourceModifiedDate?: string;
    /**
     * Identifier for the account, unique for the company in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    id?: string;
    /**
     * 
     * @type {Metadata}
     * @memberof BankAccount
     */
    metadata?: Metadata;
    /**
     * 
     * @type {SupplementalData}
     * @memberof BankAccount
     */
    supplementalData?: SupplementalData;
}


/**
 * @export
 */
export const BankAccountAccountTypeEnum = {
    Unknown: 'Unknown',
    Credit: 'Credit',
    Debit: 'Debit'
} as const;
export type BankAccountAccountTypeEnum = typeof BankAccountAccountTypeEnum[keyof typeof BankAccountAccountTypeEnum];


/**
 * Check if a given object implements the BankAccount interface.
 */
export function instanceOfBankAccount(value: object): value is BankAccount {
    return true;
}

export function BankAccountFromJSON(json: any): BankAccount {
    return BankAccountFromJSONTyped(json, false);
}

export function BankAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankAccount {
    if (json == null) {
        return json;
    }
    return {
        
        ...(json['accountName'] !== undefined ? { 'accountName': json['accountName'] } : {}),
        ...(json['accountType'] !== undefined ? { 'accountType': json['accountType'] == null ? undefined : json['accountType'] } : {}),
        ...(json['nominalCode'] !== undefined ? { 'nominalCode': json['nominalCode'] } : {}),
        ...(json['sortCode'] !== undefined ? { 'sortCode': json['sortCode'] } : {}),
        ...(json['accountNumber'] !== undefined ? { 'accountNumber': json['accountNumber'] } : {}),
        ...(json['iBan'] !== undefined ? { 'iBan': json['iBan'] } : {}),
        ...(json['currency'] !== undefined ? { 'currency': json['currency'] == null ? undefined : json['currency'] } : {}),
        ...(json['balance'] !== undefined ? { 'balance': json['balance'] == null ? json['balance'] : toDecimal(json['balance']) } : {}),
        ...(json['institution'] !== undefined ? { 'institution': json['institution'] } : {}),
        ...(json['availableBalance'] !== undefined ? { 'availableBalance': json['availableBalance'] == null ? json['availableBalance'] : toDecimal(json['availableBalance']) } : {}),
        ...(json['overdraftLimit'] !== undefined ? { 'overdraftLimit': json['overdraftLimit'] == null ? json['overdraftLimit'] : toDecimal(json['overdraftLimit']) } : {}),
        ...(json['status'] !== undefined ? { 'status': json['status'] == null ? undefined : BankAccountStatusFromJSON(json['status']) } : {}),
        ...(json['modifiedDate'] !== undefined ? { 'modifiedDate': json['modifiedDate'] == null ? undefined : json['modifiedDate'] } : {}),
        ...(json['sourceModifiedDate'] !== undefined ? { 'sourceModifiedDate': json['sourceModifiedDate'] == null ? undefined : json['sourceModifiedDate'] } : {}),
        ...(json['id'] !== undefined ? { 'id': json['id'] == null ? undefined : json['id'] } : {}),
        ...(json['metadata'] !== undefined ? { 'metadata': json['metadata'] == null ? undefined : MetadataFromJSON(json['metadata']) } : {}),
        ...(json['supplementalData'] !== undefined ? { 'supplementalData': json['supplementalData'] == null ? undefined : SupplementalDataFromJSON(json['supplementalData']) } : {}),
    };
}

export function BankAccountToJSON(json: any): BankAccount {
    return BankAccountToJSONTyped(json, false);
}

export function BankAccountToJSONTyped(value?: BankAccount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accountName': value['accountName'],
        'accountType': value['accountType'],
        'nominalCode': value['nominalCode'],
        'sortCode': value['sortCode'],
        'accountNumber': value['accountNumber'],
        'iBan': value['iBan'],
        'currency': value['currency'],
        'balance': fromDecimal(value['balance']),
        'institution': value['institution'],
        'availableBalance': fromDecimal(value['availableBalance']),
        'overdraftLimit': fromDecimal(value['overdraftLimit']),
        'status': BankAccountStatusToJSON(value['status']),
        'modifiedDate': value['modifiedDate'],
        'sourceModifiedDate': value['sourceModifiedDate'],
        'id': value['id'],
        'metadata': MetadataToJSON(value['metadata']),
        'supplementalData': SupplementalDataToJSON(value['supplementalData']),
    };
}


export interface AccountingBankAccount {
    /**
     * Name of the bank account in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    accountName?: string | null;
    /**
     * The type of transactions and balances on the account.  
     * For Credit accounts, positive balances are liabilities, and positive transactions **reduce** liabilities.  
     * For Debit accounts, positive balances are assets, and positive transactions **increase** assets.
     * @type {string}
     * @memberof BankAccount
     */
    accountType?: CreateBankAccountResponseBankAccountType;
    /**
     * Code used to identify each nominal account for a business.
     * @type {string}
     * @memberof BankAccount
     */
    nominalCode?: string | null;
    /**
     * Sort code for the bank account.
     * 
     * Xero integrations
     * The sort code is only displayed when the currency = GBP and the sort code and account number sum to 14 digits. For non-GBP accounts, this field is not populated.
     * @type {string}
     * @memberof BankAccount
     */
    sortCode?: string | null;
    /**
     * Account number for the bank account.
     * 
     * Xero integrations
     * Only a UK account number shows for bank accounts with GBP currency and a combined total of sort code and account number that equals 14 digits, For non-GBP accounts, the full bank account number is populated.
     * 
     * FreeAgent integrations
     * For Credit accounts, only the last four digits are required. For other types, the field is optional.
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber?: string | null;
    /**
     * International bank account number of the account. Often used when making or receiving international payments.
     * @type {string}
     * @memberof BankAccount
     */
    iBan?: string | null;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     * 
     * ## Unknown currencies
     * 
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction. 
     * 
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     * @type {string}
     * @memberof BankAccount
     */
    currency?: string;
    /**
     * Balance of the bank account.
     * @type {number}
     * @memberof BankAccount
     */
    balance?: Decimal | number | null;
    /**
     * The institution of the bank account.
     * @type {string}
     * @memberof BankAccount
     */
    institution?: string | null;
    /**
     * Total available balance of the bank account as reported by the underlying data source. This may take into account overdrafts or pending transactions for example.
     * @type {number}
     * @memberof BankAccount
     */
    availableBalance?: Decimal | number | null;
    /**
     * Pre-arranged overdraft limit of the account.
     * 
     * The value is always positive. For example, an overdraftLimit of `1000` means that the balance of the account can go down to `-1000`.
     * @type {number}
     * @memberof BankAccount
     */
    overdraftLimit?: Decimal | number | null;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof BankAccount
     */
    status?: BankAccountStatus;
    /**
     * The date when the record was last fetched from the accounting software, commerce software, or open banking provider and updated in Codat’s data cache.
     * 
     * Use it to identify and retrieve records that have changed since your last fetch. For example, filtering `modifiedDate` to today will provide new records updated in Codat today.
     * 
     * This date is populated for all data types except for attachments, balance sheets, company information, and profit & loss reports ([read more](https://docs.codat.io/using-the-api/modified-dates#modified-date)).
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    modifiedDate?: string;
    /**
     * The date when a record was last modified in the accounting software, usually by the business or a business process. For example, when payments are made against an invoice. 
     * 
     * It is not populated ([read more](https://docs.codat.io/using-the-api/modified-dates#source-modified-date)) when:
     *   - Pulling attachments
     *   - The accounting software does not provide modification dates for a data type
     *   - A record has been deleted from the source platform and Codat doesn't have a record of when the deletion occurred
     *   - A record has been voided. For certain platforms that soft delete records, `isDeleted` metadata is used to identify void records
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    sourceModifiedDate?: string;
    /**
     * Identifier for the account, unique for the company in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    id?: string;
    /**
     * 
     * @type {Metadata}
     * @memberof BankAccount
     */
    metadata?: Metadata;
    /**
     * 
     * @type {SupplementalData}
     * @memberof BankAccount
     */
    supplementalData?: SupplementalData;
}

export interface BankAccountAccountingBankAccount {
    /**
     * Name of the bank account in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    accountName?: string | null;
    /**
     * The type of transactions and balances on the account.  
     * For Credit accounts, positive balances are liabilities, and positive transactions **reduce** liabilities.  
     * For Debit accounts, positive balances are assets, and positive transactions **increase** assets.
     * @type {string}
     * @memberof BankAccount
     */
    accountType?: BankAccountType;
    /**
     * Code used to identify each nominal account for a business.
     * @type {string}
     * @memberof BankAccount
     */
    nominalCode?: string | null;
    /**
     * Sort code for the bank account.
     * 
     * Xero integrations
     * The sort code is only displayed when the currency = GBP and the sort code and account number sum to 14 digits. For non-GBP accounts, this field is not populated.
     * @type {string}
     * @memberof BankAccount
     */
    sortCode?: string | null;
    /**
     * Account number for the bank account.
     * 
     * Xero integrations
     * Only a UK account number shows for bank accounts with GBP currency and a combined total of sort code and account number that equals 14 digits, For non-GBP accounts, the full bank account number is populated.
     * 
     * FreeAgent integrations
     * For Credit accounts, only the last four digits are required. For other types, the field is optional.
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber?: string | null;
    /**
     * International bank account number of the account. Often used when making or receiving international payments.
     * @type {string}
     * @memberof BankAccount
     */
    iBan?: string | null;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     * 
     * ## Unknown currencies
     * 
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction. 
     * 
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     * @type {string}
     * @memberof BankAccount
     */
    currency?: string;
    /**
     * Balance of the bank account.
     * @type {number}
     * @memberof BankAccount
     */
    balance?: Decimal | number | null;
    /**
     * The institution of the bank account.
     * @type {string}
     * @memberof BankAccount
     */
    institution?: string | null;
    /**
     * Total available balance of the bank account as reported by the underlying data source. This may take into account overdrafts or pending transactions for example.
     * @type {number}
     * @memberof BankAccount
     */
    availableBalance?: Decimal | number | null;
    /**
     * Pre-arranged overdraft limit of the account.
     * 
     * The value is always positive. For example, an overdraftLimit of `1000` means that the balance of the account can go down to `-1000`.
     * @type {number}
     * @memberof BankAccount
     */
    overdraftLimit?: Decimal | number | null;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof BankAccount
     */
    status?: BankAccountStatus;
    /**
     * The date when the record was last fetched from the accounting software, commerce software, or open banking provider and updated in Codat’s data cache.
     * 
     * Use it to identify and retrieve records that have changed since your last fetch. For example, filtering `modifiedDate` to today will provide new records updated in Codat today.
     * 
     * This date is populated for all data types except for attachments, balance sheets, company information, and profit & loss reports ([read more](https://docs.codat.io/using-the-api/modified-dates#modified-date)).
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    modifiedDate?: string;
    /**
     * The date when a record was last modified in the accounting software, usually by the business or a business process. For example, when payments are made against an invoice. 
     * 
     * It is not populated ([read more](https://docs.codat.io/using-the-api/modified-dates#source-modified-date)) when:
     *   - Pulling attachments
     *   - The accounting software does not provide modification dates for a data type
     *   - A record has been deleted from the source platform and Codat doesn't have a record of when the deletion occurred
     *   - A record has been voided. For certain platforms that soft delete records, `isDeleted` metadata is used to identify void records
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    sourceModifiedDate?: string;
    /**
     * Identifier for the account, unique for the company in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    id?: string;
    /**
     * 
     * @type {Metadata}
     * @memberof BankAccount
     */
    metadata?: Metadata;
    /**
     * 
     * @type {SupplementalData}
     * @memberof BankAccount
     */
    supplementalData?: SupplementalData;
}

export interface BankAccountCreateRequestBody {
    /**
     * Name of the bank account in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    accountName?: string | null;
    /**
     * The type of transactions and balances on the account.  
     * For Credit accounts, positive balances are liabilities, and positive transactions **reduce** liabilities.  
     * For Debit accounts, positive balances are assets, and positive transactions **increase** assets.
     * @type {string}
     * @memberof BankAccount
     */
    accountType?: BankAccountType;
    /**
     * Code used to identify each nominal account for a business.
     * @type {string}
     * @memberof BankAccount
     */
    nominalCode?: string | null;
    /**
     * Sort code for the bank account.
     * 
     * Xero integrations
     * The sort code is only displayed when the currency = GBP and the sort code and account number sum to 14 digits. For non-GBP accounts, this field is not populated.
     * @type {string}
     * @memberof BankAccount
     */
    sortCode?: string | null;
    /**
     * Account number for the bank account.
     * 
     * Xero integrations
     * Only a UK account number shows for bank accounts with GBP currency and a combined total of sort code and account number that equals 14 digits, For non-GBP accounts, the full bank account number is populated.
     * 
     * FreeAgent integrations
     * For Credit accounts, only the last four digits are required. For other types, the field is optional.
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber?: string | null;
    /**
     * International bank account number of the account. Often used when making or receiving international payments.
     * @type {string}
     * @memberof BankAccount
     */
    iBan?: string | null;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     * 
     * ## Unknown currencies
     * 
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction. 
     * 
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     * @type {string}
     * @memberof BankAccount
     */
    currency?: string;
    /**
     * Balance of the bank account.
     * @type {number}
     * @memberof BankAccount
     */
    balance?: Decimal | number | null;
    /**
     * The institution of the bank account.
     * @type {string}
     * @memberof BankAccount
     */
    institution?: string | null;
    /**
     * Total available balance of the bank account as reported by the underlying data source. This may take into account overdrafts or pending transactions for example.
     * @type {number}
     * @memberof BankAccount
     */
    availableBalance?: Decimal | number | null;
    /**
     * Pre-arranged overdraft limit of the account.
     * 
     * The value is always positive. For example, an overdraftLimit of `1000` means that the balance of the account can go down to `-1000`.
     * @type {number}
     * @memberof BankAccount
     */
    overdraftLimit?: Decimal | number | null;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof BankAccount
     */
    status?: BankAccountStatus;
    /**
     * The date when the record was last fetched from the accounting software, commerce software, or open banking provider and updated in Codat’s data cache.
     * 
     * Use it to identify and retrieve records that have changed since your last fetch. For example, filtering `modifiedDate` to today will provide new records updated in Codat today.
     * 
     * This date is populated for all data types except for attachments, balance sheets, company information, and profit & loss reports ([read more](https://docs.codat.io/using-the-api/modified-dates#modified-date)).
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    modifiedDate?: string;
    /**
     * The date when a record was last modified in the accounting software, usually by the business or a business process. For example, when payments are made against an invoice. 
     * 
     * It is not populated ([read more](https://docs.codat.io/using-the-api/modified-dates#source-modified-date)) when:
     *   - Pulling attachments
     *   - The accounting software does not provide modification dates for a data type
     *   - A record has been deleted from the source platform and Codat doesn't have a record of when the deletion occurred
     *   - A record has been voided. For certain platforms that soft delete records, `isDeleted` metadata is used to identify void records
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    sourceModifiedDate?: string;
    /**
     * Identifier for the account, unique for the company in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    id?: string;
    /**
     * 
     * @type {Metadata}
     * @memberof BankAccount
     */
    metadata?: Metadata;
    /**
     * 
     * @type {SupplementalData}
     * @memberof BankAccount
     */
    supplementalData?: SupplementalData;
}

export interface BankAccountCreateResponseAccountingBankAccount {
    /**
     * Name of the bank account in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    accountName?: string | null;
    /**
     * The type of transactions and balances on the account.  
     * For Credit accounts, positive balances are liabilities, and positive transactions **reduce** liabilities.  
     * For Debit accounts, positive balances are assets, and positive transactions **increase** assets.
     * @type {string}
     * @memberof BankAccount
     */
    accountType?: BankAccountType;
    /**
     * Code used to identify each nominal account for a business.
     * @type {string}
     * @memberof BankAccount
     */
    nominalCode?: string | null;
    /**
     * Sort code for the bank account.
     * 
     * Xero integrations
     * The sort code is only displayed when the currency = GBP and the sort code and account number sum to 14 digits. For non-GBP accounts, this field is not populated.
     * @type {string}
     * @memberof BankAccount
     */
    sortCode?: string | null;
    /**
     * Account number for the bank account.
     * 
     * Xero integrations
     * Only a UK account number shows for bank accounts with GBP currency and a combined total of sort code and account number that equals 14 digits, For non-GBP accounts, the full bank account number is populated.
     * 
     * FreeAgent integrations
     * For Credit accounts, only the last four digits are required. For other types, the field is optional.
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber?: string | null;
    /**
     * International bank account number of the account. Often used when making or receiving international payments.
     * @type {string}
     * @memberof BankAccount
     */
    iBan?: string | null;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     * 
     * ## Unknown currencies
     * 
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction. 
     * 
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     * @type {string}
     * @memberof BankAccount
     */
    currency?: string;
    /**
     * Balance of the bank account.
     * @type {number}
     * @memberof BankAccount
     */
    balance?: Decimal | number | null;
    /**
     * The institution of the bank account.
     * @type {string}
     * @memberof BankAccount
     */
    institution?: string | null;
    /**
     * Total available balance of the bank account as reported by the underlying data source. This may take into account overdrafts or pending transactions for example.
     * @type {number}
     * @memberof BankAccount
     */
    availableBalance?: Decimal | number | null;
    /**
     * Pre-arranged overdraft limit of the account.
     * 
     * The value is always positive. For example, an overdraftLimit of `1000` means that the balance of the account can go down to `-1000`.
     * @type {number}
     * @memberof BankAccount
     */
    overdraftLimit?: Decimal | number | null;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof BankAccount
     */
    status?: BankAccountStatus;
    /**
     * The date when the record was last fetched from the accounting software, commerce software, or open banking provider and updated in Codat’s data cache.
     * 
     * Use it to identify and retrieve records that have changed since your last fetch. For example, filtering `modifiedDate` to today will provide new records updated in Codat today.
     * 
     * This date is populated for all data types except for attachments, balance sheets, company information, and profit & loss reports ([read more](https://docs.codat.io/using-the-api/modified-dates#modified-date)).
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    modifiedDate?: string;
    /**
     * The date when a record was last modified in the accounting software, usually by the business or a business process. For example, when payments are made against an invoice. 
     * 
     * It is not populated ([read more](https://docs.codat.io/using-the-api/modified-dates#source-modified-date)) when:
     *   - Pulling attachments
     *   - The accounting software does not provide modification dates for a data type
     *   - A record has been deleted from the source platform and Codat doesn't have a record of when the deletion occurred
     *   - A record has been voided. For certain platforms that soft delete records, `isDeleted` metadata is used to identify void records
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    sourceModifiedDate?: string;
    /**
     * Identifier for the account, unique for the company in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    id?: string;
    /**
     * 
     * @type {Metadata}
     * @memberof BankAccount
     */
    metadata?: Metadata;
    /**
     * 
     * @type {SupplementalData}
     * @memberof BankAccount
     */
    supplementalData?: SupplementalData;
}

export interface BankAccountCreateResponseBankAccount {
    /**
     * Name of the bank account in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    accountName?: string | null;
    /**
     * The type of transactions and balances on the account.  
     * For Credit accounts, positive balances are liabilities, and positive transactions **reduce** liabilities.  
     * For Debit accounts, positive balances are assets, and positive transactions **increase** assets.
     * @type {string}
     * @memberof BankAccount
     */
    accountType?: BankAccountType;
    /**
     * Code used to identify each nominal account for a business.
     * @type {string}
     * @memberof BankAccount
     */
    nominalCode?: string | null;
    /**
     * Sort code for the bank account.
     * 
     * Xero integrations
     * The sort code is only displayed when the currency = GBP and the sort code and account number sum to 14 digits. For non-GBP accounts, this field is not populated.
     * @type {string}
     * @memberof BankAccount
     */
    sortCode?: string | null;
    /**
     * Account number for the bank account.
     * 
     * Xero integrations
     * Only a UK account number shows for bank accounts with GBP currency and a combined total of sort code and account number that equals 14 digits, For non-GBP accounts, the full bank account number is populated.
     * 
     * FreeAgent integrations
     * For Credit accounts, only the last four digits are required. For other types, the field is optional.
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber?: string | null;
    /**
     * International bank account number of the account. Often used when making or receiving international payments.
     * @type {string}
     * @memberof BankAccount
     */
    iBan?: string | null;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     * 
     * ## Unknown currencies
     * 
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction. 
     * 
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     * @type {string}
     * @memberof BankAccount
     */
    currency?: string;
    /**
     * Balance of the bank account.
     * @type {number}
     * @memberof BankAccount
     */
    balance?: Decimal | number | null;
    /**
     * The institution of the bank account.
     * @type {string}
     * @memberof BankAccount
     */
    institution?: string | null;
    /**
     * Total available balance of the bank account as reported by the underlying data source. This may take into account overdrafts or pending transactions for example.
     * @type {number}
     * @memberof BankAccount
     */
    availableBalance?: Decimal | number | null;
    /**
     * Pre-arranged overdraft limit of the account.
     * 
     * The value is always positive. For example, an overdraftLimit of `1000` means that the balance of the account can go down to `-1000`.
     * @type {number}
     * @memberof BankAccount
     */
    overdraftLimit?: Decimal | number | null;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof BankAccount
     */
    status?: BankAccountStatus;
    /**
     * The date when the record was last fetched from the accounting software, commerce software, or open banking provider and updated in Codat’s data cache.
     * 
     * Use it to identify and retrieve records that have changed since your last fetch. For example, filtering `modifiedDate` to today will provide new records updated in Codat today.
     * 
     * This date is populated for all data types except for attachments, balance sheets, company information, and profit & loss reports ([read more](https://docs.codat.io/using-the-api/modified-dates#modified-date)).
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    modifiedDate?: string;
    /**
     * The date when a record was last modified in the accounting software, usually by the business or a business process. For example, when payments are made against an invoice. 
     * 
     * It is not populated ([read more](https://docs.codat.io/using-the-api/modified-dates#source-modified-date)) when:
     *   - Pulling attachments
     *   - The accounting software does not provide modification dates for a data type
     *   - A record has been deleted from the source platform and Codat doesn't have a record of when the deletion occurred
     *   - A record has been voided. For certain platforms that soft delete records, `isDeleted` metadata is used to identify void records
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    sourceModifiedDate?: string;
    /**
     * Identifier for the account, unique for the company in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    id?: string;
    /**
     * 
     * @type {Metadata}
     * @memberof BankAccount
     */
    metadata?: Metadata;
    /**
     * 
     * @type {SupplementalData}
     * @memberof BankAccount
     */
    supplementalData?: SupplementalData;
}

export interface CreateBankAccountBankAccount {
    /**
     * Name of the bank account in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    accountName?: string | null;
    /**
     * The type of transactions and balances on the account.  
     * For Credit accounts, positive balances are liabilities, and positive transactions **reduce** liabilities.  
     * For Debit accounts, positive balances are assets, and positive transactions **increase** assets.
     * @type {string}
     * @memberof BankAccount
     */
    accountType?: BankAccountType;
    /**
     * Code used to identify each nominal account for a business.
     * @type {string}
     * @memberof BankAccount
     */
    nominalCode?: string | null;
    /**
     * Sort code for the bank account.
     * 
     * Xero integrations
     * The sort code is only displayed when the currency = GBP and the sort code and account number sum to 14 digits. For non-GBP accounts, this field is not populated.
     * @type {string}
     * @memberof BankAccount
     */
    sortCode?: string | null;
    /**
     * Account number for the bank account.
     * 
     * Xero integrations
     * Only a UK account number shows for bank accounts with GBP currency and a combined total of sort code and account number that equals 14 digits, For non-GBP accounts, the full bank account number is populated.
     * 
     * FreeAgent integrations
     * For Credit accounts, only the last four digits are required. For other types, the field is optional.
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber?: string | null;
    /**
     * International bank account number of the account. Often used when making or receiving international payments.
     * @type {string}
     * @memberof BankAccount
     */
    iBan?: string | null;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     * 
     * ## Unknown currencies
     * 
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction. 
     * 
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     * @type {string}
     * @memberof BankAccount
     */
    currency?: string;
    /**
     * Balance of the bank account.
     * @type {number}
     * @memberof BankAccount
     */
    balance?: Decimal | number | null;
    /**
     * The institution of the bank account.
     * @type {string}
     * @memberof BankAccount
     */
    institution?: string | null;
    /**
     * Total available balance of the bank account as reported by the underlying data source. This may take into account overdrafts or pending transactions for example.
     * @type {number}
     * @memberof BankAccount
     */
    availableBalance?: Decimal | number | null;
    /**
     * Pre-arranged overdraft limit of the account.
     * 
     * The value is always positive. For example, an overdraftLimit of `1000` means that the balance of the account can go down to `-1000`.
     * @type {number}
     * @memberof BankAccount
     */
    overdraftLimit?: Decimal | number | null;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof BankAccount
     */
    status?: BankAccountStatus;
    /**
     * The date when the record was last fetched from the accounting software, commerce software, or open banking provider and updated in Codat’s data cache.
     * 
     * Use it to identify and retrieve records that have changed since your last fetch. For example, filtering `modifiedDate` to today will provide new records updated in Codat today.
     * 
     * This date is populated for all data types except for attachments, balance sheets, company information, and profit & loss reports ([read more](https://docs.codat.io/using-the-api/modified-dates#modified-date)).
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    modifiedDate?: string;
    /**
     * The date when a record was last modified in the accounting software, usually by the business or a business process. For example, when payments are made against an invoice. 
     * 
     * It is not populated ([read more](https://docs.codat.io/using-the-api/modified-dates#source-modified-date)) when:
     *   - Pulling attachments
     *   - The accounting software does not provide modification dates for a data type
     *   - A record has been deleted from the source platform and Codat doesn't have a record of when the deletion occurred
     *   - A record has been voided. For certain platforms that soft delete records, `isDeleted` metadata is used to identify void records
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    sourceModifiedDate?: string;
    /**
     * Identifier for the account, unique for the company in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    id?: string;
    /**
     * 
     * @type {Metadata}
     * @memberof BankAccount
     */
    metadata?: Metadata;
    /**
     * 
     * @type {SupplementalData}
     * @memberof BankAccount
     */
    supplementalData?: SupplementalData;
}

export interface CreateBankAccountRequestBody {
    /**
     * Name of the bank account in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    accountName?: string | null;
    /**
     * The type of transactions and balances on the account.  
     * For Credit accounts, positive balances are liabilities, and positive transactions **reduce** liabilities.  
     * For Debit accounts, positive balances are assets, and positive transactions **increase** assets.
     * @type {string}
     * @memberof BankAccount
     */
    accountType?: BankAccountType;
    /**
     * Code used to identify each nominal account for a business.
     * @type {string}
     * @memberof BankAccount
     */
    nominalCode?: string | null;
    /**
     * Sort code for the bank account.
     * 
     * Xero integrations
     * The sort code is only displayed when the currency = GBP and the sort code and account number sum to 14 digits. For non-GBP accounts, this field is not populated.
     * @type {string}
     * @memberof BankAccount
     */
    sortCode?: string | null;
    /**
     * Account number for the bank account.
     * 
     * Xero integrations
     * Only a UK account number shows for bank accounts with GBP currency and a combined total of sort code and account number that equals 14 digits, For non-GBP accounts, the full bank account number is populated.
     * 
     * FreeAgent integrations
     * For Credit accounts, only the last four digits are required. For other types, the field is optional.
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber?: string | null;
    /**
     * International bank account number of the account. Often used when making or receiving international payments.
     * @type {string}
     * @memberof BankAccount
     */
    iBan?: string | null;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     * 
     * ## Unknown currencies
     * 
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction. 
     * 
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     * @type {string}
     * @memberof BankAccount
     */
    currency?: string;
    /**
     * Balance of the bank account.
     * @type {number}
     * @memberof BankAccount
     */
    balance?: Decimal | number | null;
    /**
     * The institution of the bank account.
     * @type {string}
     * @memberof BankAccount
     */
    institution?: string | null;
    /**
     * Total available balance of the bank account as reported by the underlying data source. This may take into account overdrafts or pending transactions for example.
     * @type {number}
     * @memberof BankAccount
     */
    availableBalance?: Decimal | number | null;
    /**
     * Pre-arranged overdraft limit of the account.
     * 
     * The value is always positive. For example, an overdraftLimit of `1000` means that the balance of the account can go down to `-1000`.
     * @type {number}
     * @memberof BankAccount
     */
    overdraftLimit?: Decimal | number | null;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof BankAccount
     */
    status?: BankAccountStatus;
    /**
     * The date when the record was last fetched from the accounting software, commerce software, or open banking provider and updated in Codat’s data cache.
     * 
     * Use it to identify and retrieve records that have changed since your last fetch. For example, filtering `modifiedDate` to today will provide new records updated in Codat today.
     * 
     * This date is populated for all data types except for attachments, balance sheets, company information, and profit & loss reports ([read more](https://docs.codat.io/using-the-api/modified-dates#modified-date)).
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    modifiedDate?: string;
    /**
     * The date when a record was last modified in the accounting software, usually by the business or a business process. For example, when payments are made against an invoice. 
     * 
     * It is not populated ([read more](https://docs.codat.io/using-the-api/modified-dates#source-modified-date)) when:
     *   - Pulling attachments
     *   - The accounting software does not provide modification dates for a data type
     *   - A record has been deleted from the source platform and Codat doesn't have a record of when the deletion occurred
     *   - A record has been voided. For certain platforms that soft delete records, `isDeleted` metadata is used to identify void records
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    sourceModifiedDate?: string;
    /**
     * Identifier for the account, unique for the company in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    id?: string;
    /**
     * 
     * @type {Metadata}
     * @memberof BankAccount
     */
    metadata?: Metadata;
    /**
     * 
     * @type {SupplementalData}
     * @memberof BankAccount
     */
    supplementalData?: SupplementalData;
}

export interface CreateBankAccountResponseAccountingBankAccount {
    /**
     * Name of the bank account in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    accountName?: string | null;
    /**
     * The type of transactions and balances on the account.  
     * For Credit accounts, positive balances are liabilities, and positive transactions **reduce** liabilities.  
     * For Debit accounts, positive balances are assets, and positive transactions **increase** assets.
     * @type {string}
     * @memberof BankAccount
     */
    accountType?: BankAccountType;
    /**
     * Code used to identify each nominal account for a business.
     * @type {string}
     * @memberof BankAccount
     */
    nominalCode?: string | null;
    /**
     * Sort code for the bank account.
     * 
     * Xero integrations
     * The sort code is only displayed when the currency = GBP and the sort code and account number sum to 14 digits. For non-GBP accounts, this field is not populated.
     * @type {string}
     * @memberof BankAccount
     */
    sortCode?: string | null;
    /**
     * Account number for the bank account.
     * 
     * Xero integrations
     * Only a UK account number shows for bank accounts with GBP currency and a combined total of sort code and account number that equals 14 digits, For non-GBP accounts, the full bank account number is populated.
     * 
     * FreeAgent integrations
     * For Credit accounts, only the last four digits are required. For other types, the field is optional.
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber?: string | null;
    /**
     * International bank account number of the account. Often used when making or receiving international payments.
     * @type {string}
     * @memberof BankAccount
     */
    iBan?: string | null;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     * 
     * ## Unknown currencies
     * 
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction. 
     * 
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     * @type {string}
     * @memberof BankAccount
     */
    currency?: string;
    /**
     * Balance of the bank account.
     * @type {number}
     * @memberof BankAccount
     */
    balance?: Decimal | number | null;
    /**
     * The institution of the bank account.
     * @type {string}
     * @memberof BankAccount
     */
    institution?: string | null;
    /**
     * Total available balance of the bank account as reported by the underlying data source. This may take into account overdrafts or pending transactions for example.
     * @type {number}
     * @memberof BankAccount
     */
    availableBalance?: Decimal | number | null;
    /**
     * Pre-arranged overdraft limit of the account.
     * 
     * The value is always positive. For example, an overdraftLimit of `1000` means that the balance of the account can go down to `-1000`.
     * @type {number}
     * @memberof BankAccount
     */
    overdraftLimit?: Decimal | number | null;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof BankAccount
     */
    status?: BankAccountStatus;
    /**
     * The date when the record was last fetched from the accounting software, commerce software, or open banking provider and updated in Codat’s data cache.
     * 
     * Use it to identify and retrieve records that have changed since your last fetch. For example, filtering `modifiedDate` to today will provide new records updated in Codat today.
     * 
     * This date is populated for all data types except for attachments, balance sheets, company information, and profit & loss reports ([read more](https://docs.codat.io/using-the-api/modified-dates#modified-date)).
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    modifiedDate?: string;
    /**
     * The date when a record was last modified in the accounting software, usually by the business or a business process. For example, when payments are made against an invoice. 
     * 
     * It is not populated ([read more](https://docs.codat.io/using-the-api/modified-dates#source-modified-date)) when:
     *   - Pulling attachments
     *   - The accounting software does not provide modification dates for a data type
     *   - A record has been deleted from the source platform and Codat doesn't have a record of when the deletion occurred
     *   - A record has been voided. For certain platforms that soft delete records, `isDeleted` metadata is used to identify void records
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    sourceModifiedDate?: string;
    /**
     * Identifier for the account, unique for the company in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    id?: string;
    /**
     * 
     * @type {Metadata}
     * @memberof BankAccount
     */
    metadata?: Metadata;
    /**
     * 
     * @type {SupplementalData}
     * @memberof BankAccount
     */
    supplementalData?: SupplementalData;
}

export interface CreateBankAccountResponseBankAccount {
    /**
     * Name of the bank account in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    accountName?: string | null;
    /**
     * The type of transactions and balances on the account.  
     * For Credit accounts, positive balances are liabilities, and positive transactions **reduce** liabilities.  
     * For Debit accounts, positive balances are assets, and positive transactions **increase** assets.
     * @type {string}
     * @memberof BankAccount
     */
    accountType?: BankAccountType;
    /**
     * Code used to identify each nominal account for a business.
     * @type {string}
     * @memberof BankAccount
     */
    nominalCode?: string | null;
    /**
     * Sort code for the bank account.
     * 
     * Xero integrations
     * The sort code is only displayed when the currency = GBP and the sort code and account number sum to 14 digits. For non-GBP accounts, this field is not populated.
     * @type {string}
     * @memberof BankAccount
     */
    sortCode?: string | null;
    /**
     * Account number for the bank account.
     * 
     * Xero integrations
     * Only a UK account number shows for bank accounts with GBP currency and a combined total of sort code and account number that equals 14 digits, For non-GBP accounts, the full bank account number is populated.
     * 
     * FreeAgent integrations
     * For Credit accounts, only the last four digits are required. For other types, the field is optional.
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber?: string | null;
    /**
     * International bank account number of the account. Often used when making or receiving international payments.
     * @type {string}
     * @memberof BankAccount
     */
    iBan?: string | null;
    /**
     * The currency data type in Codat is the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code, e.g. _GBP_.
     * 
     * ## Unknown currencies
     * 
     * In line with the ISO 4217 specification, the code _XXX_ is used when the data source does not return a currency for a transaction. 
     * 
     * There are only a very small number of edge cases where this currency code is returned by the Codat system.
     * @type {string}
     * @memberof BankAccount
     */
    currency?: string;
    /**
     * Balance of the bank account.
     * @type {number}
     * @memberof BankAccount
     */
    balance?: Decimal | number | null;
    /**
     * The institution of the bank account.
     * @type {string}
     * @memberof BankAccount
     */
    institution?: string | null;
    /**
     * Total available balance of the bank account as reported by the underlying data source. This may take into account overdrafts or pending transactions for example.
     * @type {number}
     * @memberof BankAccount
     */
    availableBalance?: Decimal | number | null;
    /**
     * Pre-arranged overdraft limit of the account.
     * 
     * The value is always positive. For example, an overdraftLimit of `1000` means that the balance of the account can go down to `-1000`.
     * @type {number}
     * @memberof BankAccount
     */
    overdraftLimit?: Decimal | number | null;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof BankAccount
     */
    status?: BankAccountStatus;
    /**
     * The date when the record was last fetched from the accounting software, commerce software, or open banking provider and updated in Codat’s data cache.
     * 
     * Use it to identify and retrieve records that have changed since your last fetch. For example, filtering `modifiedDate` to today will provide new records updated in Codat today.
     * 
     * This date is populated for all data types except for attachments, balance sheets, company information, and profit & loss reports ([read more](https://docs.codat.io/using-the-api/modified-dates#modified-date)).
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    modifiedDate?: string;
    /**
     * The date when a record was last modified in the accounting software, usually by the business or a business process. For example, when payments are made against an invoice. 
     * 
     * It is not populated ([read more](https://docs.codat.io/using-the-api/modified-dates#source-modified-date)) when:
     *   - Pulling attachments
     *   - The accounting software does not provide modification dates for a data type
     *   - A record has been deleted from the source platform and Codat doesn't have a record of when the deletion occurred
     *   - A record has been voided. For certain platforms that soft delete records, `isDeleted` metadata is used to identify void records
     * 
     * In Codat's data model, dates and times are represented using the <a class="external" href="https://en.wikipedia.org/wiki/ISO_8601" target="_blank">ISO 8601 standard</a>.
     * @type {string}
     * @memberof BankAccount
     */
    sourceModifiedDate?: string;
    /**
     * Identifier for the account, unique for the company in the accounting software.
     * @type {string}
     * @memberof BankAccount
     */
    id?: string;
    /**
     * 
     * @type {Metadata}
     * @memberof BankAccount
     */
    metadata?: Metadata;
    /**
     * 
     * @type {SupplementalData}
     * @memberof BankAccount
     */
    supplementalData?: SupplementalData;
}
