/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateReimbursableExpenseResponse = {
    /**
     * Unique id of sync created
     */
    syncId?: string | undefined;
};

/** @internal */
export const CreateReimbursableExpenseResponse$inboundSchema: z.ZodType<
    CreateReimbursableExpenseResponse,
    z.ZodTypeDef,
    unknown
> = z.object({
    syncId: z.string().optional(),
});

/** @internal */
export type CreateReimbursableExpenseResponse$Outbound = {
    syncId?: string | undefined;
};

/** @internal */
export const CreateReimbursableExpenseResponse$outboundSchema: z.ZodType<
    CreateReimbursableExpenseResponse$Outbound,
    z.ZodTypeDef,
    CreateReimbursableExpenseResponse
> = z.object({
    syncId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateReimbursableExpenseResponse$ {
    /** @deprecated use `CreateReimbursableExpenseResponse$inboundSchema` instead. */
    export const inboundSchema = CreateReimbursableExpenseResponse$inboundSchema;
    /** @deprecated use `CreateReimbursableExpenseResponse$outboundSchema` instead. */
    export const outboundSchema = CreateReimbursableExpenseResponse$outboundSchema;
    /** @deprecated use `CreateReimbursableExpenseResponse$Outbound` instead. */
    export type Outbound = CreateReimbursableExpenseResponse$Outbound;
}
