/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * The type of phone number
 */
export const ItemsType = {
  Primary: "Primary",
  Landline: "Landline",
  Mobile: "Mobile",
  Fax: "Fax",
  Unknown: "Unknown",
} as const;
/**
 * The type of phone number
 */
export type ItemsType = ClosedEnum<typeof ItemsType>;

export type PhoneNumberItems = {
  /**
   * A phone number.
   */
  number?: string | null | undefined;
  /**
   * The type of phone number
   */
  type: ItemsType;
};

/** @internal */
export const ItemsType$inboundSchema: z.ZodNativeEnum<typeof ItemsType> = z
  .nativeEnum(ItemsType);
/** @internal */
export const ItemsType$outboundSchema: z.ZodNativeEnum<typeof ItemsType> =
  ItemsType$inboundSchema;

/** @internal */
export const PhoneNumberItems$inboundSchema: z.ZodType<
  PhoneNumberItems,
  z.ZodTypeDef,
  unknown
> = z.object({
  number: z.nullable(z.string()).optional(),
  type: ItemsType$inboundSchema,
});
/** @internal */
export type PhoneNumberItems$Outbound = {
  number?: string | null | undefined;
  type: string;
};

/** @internal */
export const PhoneNumberItems$outboundSchema: z.ZodType<
  PhoneNumberItems$Outbound,
  z.ZodTypeDef,
  PhoneNumberItems
> = z.object({
  number: z.nullable(z.string()).optional(),
  type: ItemsType$outboundSchema,
});

export function phoneNumberItemsToJSON(
  phoneNumberItems: PhoneNumberItems,
): string {
  return JSON.stringify(
    PhoneNumberItems$outboundSchema.parse(phoneNumberItems),
  );
}
export function phoneNumberItemsFromJSON(
  jsonString: string,
): SafeParseResult<PhoneNumberItems, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PhoneNumberItems$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PhoneNumberItems' from JSON`,
  );
}
