/* tslint:disable */
/* eslint-disable */
/**
 * Expenses
 * The API for Codat\'s Expenses solution.  Expenses is an API and a set of supporting tools. It has been built to enable corporate card and expense management platforms to provide high-quality integrations with multiple accounting software through a standardized API.  [Explore solution](https://docs.codat.io/sync-for-expenses/overview) | [See our OpenAPI spec](https://github.com/codatio/oas)  Not seeing the endpoints you\'re expecting? We\'ve [reorganized our solutions](https://docs.codat.io/updates/230901-new-products), and you may be using a [different version of Expenses](https://docs.codat.io/sync-for-expenses-v1-api#/).  --- <!-- Start Codat Tags Table --> ## Endpoints  | Endpoints | Description | | :- |:- | | Companies | Create and manage your SMB users\' companies. | | Connections | Create new and manage existing data connections for a company. | | Configuration | View and manage mapping configuration and defaults for expense transactions. | | Sync | Monitor the status of data syncs. | | Expenses | Create and update transactions that represent your customers\' spend. | | Transfers | Create and update transactions that represent the movement of your customers\' money. | | Reimbursements | Create and update transactions that represent your customers\' repayable spend. | | Attachments | Attach receipts to a transaction for a complete audit trail. | | Transaction status | Monitor the status of individual transactions in data syncs. | | Manage data | Control and monitor the retrieval of data from an integration. | | Push operations | View historic push operations. | | Accounts | Create accounts and view account schemas. | | Customers | Get, create, and update customers. | | Suppliers | Get, create, and update suppliers. | <!-- End Codat Tags Table -->
 *
 * The version of the OpenAPI document: prealpha
 * Contact: expenses@codat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DatasetStatus } from '../_speakeasy_enums';
import { mapValues } from '../../../runtime';
/**
 * Information about a queued, in progress or completed pull operation.
 * *Formally called `dataset`*
 * @export
 * @interface PullOperation
 */
export interface PullOperation {
    /**
     * Unique identifier of the pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    id: string;
    /**
     * Unique identifier of the company associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    companyId: string;
    /**
     * Unique identifier of the connection associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    connectionId: string;
    /**
     * The data type you are requesting in a pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    dataType: string;
    /**
     * The current status of the dataset.
     * @type {string}
     * @memberof PullOperation
     */
    status: DatasetStatus;
    /**
     * Additional information about the dataset status.
     * @type {string}
     * @memberof PullOperation
     */
    statusDescription?: string | null;
    /**
     * A message about a transient or persistent error returned by Codat or the source platform.
     * @type {string}
     * @memberof PullOperation
     */
    errorMessage?: string | null;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    requested: string;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    completed?: string;
    /**
     * An integer signifying the progress of the pull operation.
     * @type {number}
     * @memberof PullOperation
     */
    progress: number;
    /**
     * `True` if the pull operation is completed successfully. The `isCompleted` property is not queryable. To filter failed pull operations, query by `status!=Complete&&status!=NotSupported` instead.
     * @type {boolean}
     * @memberof PullOperation
     */
    isCompleted: boolean;
    /**
     * `True` if the pull operation entered an error state.
     * @type {boolean}
     * @memberof PullOperation
     */
    isErrored: boolean;
}


/**
 * @export
 */
export const PullOperationStatusEnum = {
    Initial: 'Initial',
    Queued: 'Queued',
    Fetching: 'Fetching',
    MapQueued: 'MapQueued',
    Mapping: 'Mapping',
    Complete: 'Complete',
    FetchError: 'FetchError',
    MapError: 'MapError',
    InternalError: 'InternalError',
    ProcessingQueued: 'ProcessingQueued',
    Processing: 'Processing',
    ProcessingError: 'ProcessingError',
    ValidationQueued: 'ValidationQueued',
    Validating: 'Validating',
    ValidationError: 'ValidationError',
    AuthError: 'AuthError',
    Cancelled: 'Cancelled',
    NotSupported: 'NotSupported',
    RateLimitError: 'RateLimitError',
    PermissionsError: 'PermissionsError',
    PrerequisiteNotMet: 'PrerequisiteNotMet'
} as const;
export type PullOperationStatusEnum = typeof PullOperationStatusEnum[keyof typeof PullOperationStatusEnum];


/**
 * Check if a given object implements the PullOperation interface.
 */
export function instanceOfPullOperation(value: object): value is PullOperation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    if (!('connectionId' in value) || value['connectionId'] === undefined) return false;
    if (!('dataType' in value) || value['dataType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('requested' in value) || value['requested'] === undefined) return false;
    if (!('progress' in value) || value['progress'] === undefined) return false;
    if (!('isCompleted' in value) || value['isCompleted'] === undefined) return false;
    if (!('isErrored' in value) || value['isErrored'] === undefined) return false;
    return true;
}

export function PullOperationFromJSON(json: any): PullOperation {
    return PullOperationFromJSONTyped(json, false);
}

export function PullOperationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PullOperation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'companyId': json['companyId'],
        'connectionId': json['connectionId'],
        'dataType': json['dataType'],
        'status': json['status'],
        'statusDescription': json['statusDescription'] == null ? undefined : json['statusDescription'],
        'errorMessage': json['errorMessage'] == null ? undefined : json['errorMessage'],
        'requested': json['requested'],
        'completed': json['completed'] == null ? undefined : json['completed'],
        'progress': json['progress'],
        'isCompleted': json['isCompleted'],
        'isErrored': json['isErrored'],
    };
}

export function PullOperationToJSON(json: any): PullOperation {
    return PullOperationToJSONTyped(json, false);
}

export function PullOperationToJSONTyped(value?: PullOperation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'companyId': value['companyId'],
        'connectionId': value['connectionId'],
        'dataType': value['dataType'],
        'status': value['status'],
        'statusDescription': value['statusDescription'],
        'errorMessage': value['errorMessage'],
        'requested': value['requested'],
        'completed': value['completed'],
        'progress': value['progress'],
        'isCompleted': value['isCompleted'],
        'isErrored': value['isErrored'],
    };
}


export interface DataTypeRefreshResponsePullOperation {
    /**
     * Unique identifier of the pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    id: string;
    /**
     * Unique identifier of the company associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    companyId: string;
    /**
     * Unique identifier of the connection associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    connectionId: string;
    /**
     * The data type you are requesting in a pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    dataType: string;
    /**
     * The current status of the dataset.
     * @type {string}
     * @memberof PullOperation
     */
    status: DatasetStatus;
    /**
     * Additional information about the dataset status.
     * @type {string}
     * @memberof PullOperation
     */
    statusDescription?: string | null;
    /**
     * A message about a transient or persistent error returned by Codat or the source platform.
     * @type {string}
     * @memberof PullOperation
     */
    errorMessage?: string | null;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    requested: string;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    completed?: string;
    /**
     * An integer signifying the progress of the pull operation.
     * @type {number}
     * @memberof PullOperation
     */
    progress: number;
    /**
     * `True` if the pull operation is completed successfully. The `isCompleted` property is not queryable. To filter failed pull operations, query by `status!=Complete&&status!=NotSupported` instead.
     * @type {boolean}
     * @memberof PullOperation
     */
    isCompleted: boolean;
    /**
     * `True` if the pull operation entered an error state.
     * @type {boolean}
     * @memberof PullOperation
     */
    isErrored: boolean;
}

export interface GetPullOperationResponsePullOperation {
    /**
     * Unique identifier of the pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    id: string;
    /**
     * Unique identifier of the company associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    companyId: string;
    /**
     * Unique identifier of the connection associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    connectionId: string;
    /**
     * The data type you are requesting in a pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    dataType: string;
    /**
     * The current status of the dataset.
     * @type {string}
     * @memberof PullOperation
     */
    status: DatasetStatus;
    /**
     * Additional information about the dataset status.
     * @type {string}
     * @memberof PullOperation
     */
    statusDescription?: string | null;
    /**
     * A message about a transient or persistent error returned by Codat or the source platform.
     * @type {string}
     * @memberof PullOperation
     */
    errorMessage?: string | null;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    requested: string;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    completed?: string;
    /**
     * An integer signifying the progress of the pull operation.
     * @type {number}
     * @memberof PullOperation
     */
    progress: number;
    /**
     * `True` if the pull operation is completed successfully. The `isCompleted` property is not queryable. To filter failed pull operations, query by `status!=Complete&&status!=NotSupported` instead.
     * @type {boolean}
     * @memberof PullOperation
     */
    isCompleted: boolean;
    /**
     * `True` if the pull operation entered an error state.
     * @type {boolean}
     * @memberof PullOperation
     */
    isErrored: boolean;
}

export interface ListPullOperationsResponsePullOperation {
    /**
     * Unique identifier of the pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    id: string;
    /**
     * Unique identifier of the company associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    companyId: string;
    /**
     * Unique identifier of the connection associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    connectionId: string;
    /**
     * The data type you are requesting in a pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    dataType: string;
    /**
     * The current status of the dataset.
     * @type {string}
     * @memberof PullOperation
     */
    status: DatasetStatus;
    /**
     * Additional information about the dataset status.
     * @type {string}
     * @memberof PullOperation
     */
    statusDescription?: string | null;
    /**
     * A message about a transient or persistent error returned by Codat or the source platform.
     * @type {string}
     * @memberof PullOperation
     */
    errorMessage?: string | null;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    requested: string;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    completed?: string;
    /**
     * An integer signifying the progress of the pull operation.
     * @type {number}
     * @memberof PullOperation
     */
    progress: number;
    /**
     * `True` if the pull operation is completed successfully. The `isCompleted` property is not queryable. To filter failed pull operations, query by `status!=Complete&&status!=NotSupported` instead.
     * @type {boolean}
     * @memberof PullOperation
     */
    isCompleted: boolean;
    /**
     * `True` if the pull operation entered an error state.
     * @type {boolean}
     * @memberof PullOperation
     */
    isErrored: boolean;
}

export interface PullOperationGetResponsePullOperation {
    /**
     * Unique identifier of the pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    id: string;
    /**
     * Unique identifier of the company associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    companyId: string;
    /**
     * Unique identifier of the connection associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    connectionId: string;
    /**
     * The data type you are requesting in a pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    dataType: string;
    /**
     * The current status of the dataset.
     * @type {string}
     * @memberof PullOperation
     */
    status: DatasetStatus;
    /**
     * Additional information about the dataset status.
     * @type {string}
     * @memberof PullOperation
     */
    statusDescription?: string | null;
    /**
     * A message about a transient or persistent error returned by Codat or the source platform.
     * @type {string}
     * @memberof PullOperation
     */
    errorMessage?: string | null;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    requested: string;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    completed?: string;
    /**
     * An integer signifying the progress of the pull operation.
     * @type {number}
     * @memberof PullOperation
     */
    progress: number;
    /**
     * `True` if the pull operation is completed successfully. The `isCompleted` property is not queryable. To filter failed pull operations, query by `status!=Complete&&status!=NotSupported` instead.
     * @type {boolean}
     * @memberof PullOperation
     */
    isCompleted: boolean;
    /**
     * `True` if the pull operation entered an error state.
     * @type {boolean}
     * @memberof PullOperation
     */
    isErrored: boolean;
}

export interface PullOperationsListResponsePullOperation {
    /**
     * Unique identifier of the pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    id: string;
    /**
     * Unique identifier of the company associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    companyId: string;
    /**
     * Unique identifier of the connection associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    connectionId: string;
    /**
     * The data type you are requesting in a pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    dataType: string;
    /**
     * The current status of the dataset.
     * @type {string}
     * @memberof PullOperation
     */
    status: DatasetStatus;
    /**
     * Additional information about the dataset status.
     * @type {string}
     * @memberof PullOperation
     */
    statusDescription?: string | null;
    /**
     * A message about a transient or persistent error returned by Codat or the source platform.
     * @type {string}
     * @memberof PullOperation
     */
    errorMessage?: string | null;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    requested: string;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    completed?: string;
    /**
     * An integer signifying the progress of the pull operation.
     * @type {number}
     * @memberof PullOperation
     */
    progress: number;
    /**
     * `True` if the pull operation is completed successfully. The `isCompleted` property is not queryable. To filter failed pull operations, query by `status!=Complete&&status!=NotSupported` instead.
     * @type {boolean}
     * @memberof PullOperation
     */
    isCompleted: boolean;
    /**
     * `True` if the pull operation entered an error state.
     * @type {boolean}
     * @memberof PullOperation
     */
    isErrored: boolean;
}

export interface PullOperationsPullOperation {
    /**
     * Unique identifier of the pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    id: string;
    /**
     * Unique identifier of the company associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    companyId: string;
    /**
     * Unique identifier of the connection associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    connectionId: string;
    /**
     * The data type you are requesting in a pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    dataType: string;
    /**
     * The current status of the dataset.
     * @type {string}
     * @memberof PullOperation
     */
    status: DatasetStatus;
    /**
     * Additional information about the dataset status.
     * @type {string}
     * @memberof PullOperation
     */
    statusDescription?: string | null;
    /**
     * A message about a transient or persistent error returned by Codat or the source platform.
     * @type {string}
     * @memberof PullOperation
     */
    errorMessage?: string | null;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    requested: string;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    completed?: string;
    /**
     * An integer signifying the progress of the pull operation.
     * @type {number}
     * @memberof PullOperation
     */
    progress: number;
    /**
     * `True` if the pull operation is completed successfully. The `isCompleted` property is not queryable. To filter failed pull operations, query by `status!=Complete&&status!=NotSupported` instead.
     * @type {boolean}
     * @memberof PullOperation
     */
    isCompleted: boolean;
    /**
     * `True` if the pull operation entered an error state.
     * @type {boolean}
     * @memberof PullOperation
     */
    isErrored: boolean;
}

export interface RefreshDataTypeResponsePullOperation {
    /**
     * Unique identifier of the pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    id: string;
    /**
     * Unique identifier of the company associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    companyId: string;
    /**
     * Unique identifier of the connection associated to this pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    connectionId: string;
    /**
     * The data type you are requesting in a pull operation.
     * @type {string}
     * @memberof PullOperation
     */
    dataType: string;
    /**
     * The current status of the dataset.
     * @type {string}
     * @memberof PullOperation
     */
    status: DatasetStatus;
    /**
     * Additional information about the dataset status.
     * @type {string}
     * @memberof PullOperation
     */
    statusDescription?: string | null;
    /**
     * A message about a transient or persistent error returned by Codat or the source platform.
     * @type {string}
     * @memberof PullOperation
     */
    errorMessage?: string | null;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    requested: string;
    /**
     * Date of the transfer transaction as recorded in the accounting software.
     * @type {string}
     * @memberof PullOperation
     */
    completed?: string;
    /**
     * An integer signifying the progress of the pull operation.
     * @type {number}
     * @memberof PullOperation
     */
    progress: number;
    /**
     * `True` if the pull operation is completed successfully. The `isCompleted` property is not queryable. To filter failed pull operations, query by `status!=Complete&&status!=NotSupported` instead.
     * @type {boolean}
     * @memberof PullOperation
     */
    isCompleted: boolean;
    /**
     * `True` if the pull operation entered an error state.
     * @type {boolean}
     * @memberof PullOperation
     */
    isErrored: boolean;
}
