/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

/**
 * The current status of the dataset.
 */
export const Status = {
    Initial: "Initial",
    Queued: "Queued",
    Fetching: "Fetching",
    MapQueued: "MapQueued",
    Mapping: "Mapping",
    Complete: "Complete",
    FetchError: "FetchError",
    MapError: "MapError",
    InternalError: "InternalError",
    ProcessingQueued: "ProcessingQueued",
    Processing: "Processing",
    ProcessingError: "ProcessingError",
    ValidationQueued: "ValidationQueued",
    Validating: "Validating",
    ValidationError: "ValidationError",
    AuthError: "AuthError",
    Cancelled: "Cancelled",
    NotSupported: "NotSupported",
    RateLimitError: "RateLimitError",
    PermissionsError: "PermissionsError",
    PrerequisiteNotMet: "PrerequisiteNotMet",
} as const;
/**
 * The current status of the dataset.
 */
export type Status = ClosedEnum<typeof Status>;

/** @internal */
export const Status$inboundSchema: z.ZodNativeEnum<typeof Status> = z.nativeEnum(Status);

/** @internal */
export const Status$outboundSchema: z.ZodNativeEnum<typeof Status> = Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Status$ {
    /** @deprecated use `Status$inboundSchema` instead. */
    export const inboundSchema = Status$inboundSchema;
    /** @deprecated use `Status$outboundSchema` instead. */
    export const outboundSchema = Status$outboundSchema;
}
