/* tslint:disable */
/* eslint-disable */
/**
 * Expenses
 * The API for Codat\'s Expenses solution.  Expenses is an API and a set of supporting tools. It has been built to enable corporate card and expense management platforms to provide high-quality integrations with multiple accounting software through a standardized API.  [Explore solution](https://docs.codat.io/sync-for-expenses/overview) | [See our OpenAPI spec](https://github.com/codatio/oas)  Not seeing the endpoints you\'re expecting? We\'ve [reorganized our solutions](https://docs.codat.io/updates/230901-new-products), and you may be using a [different version of Expenses](https://docs.codat.io/sync-for-expenses-v1-api#/).  --- <!-- Start Codat Tags Table --> ## Endpoints  | Endpoints | Description | | :- |:- | | Companies | Create and manage your SMB users\' companies. | | Connections | Create new and manage existing data connections for a company. | | Configuration | View and manage mapping configuration and defaults for expense transactions. | | Sync | Monitor the status of data syncs. | | Expenses | Create and update transactions that represent your customers\' spend. | | Transfers | Create and update transactions that represent the movement of your customers\' money. | | Reimbursements | Create and update transactions that represent your customers\' repayable spend. | | Attachments | Attach receipts to a transaction for a complete audit trail. | | Transaction status | Monitor the status of individual transactions in data syncs. | | Manage data | Control and monitor the retrieval of data from an integration. | | Push operations | View historic push operations. | | Accounts | Create accounts and view account schemas. | | Customers | Get, create, and update customers. | | Suppliers | Get, create, and update suppliers. | <!-- End Codat Tags Table -->
 *
 * The version of the OpenAPI document: prealpha
 * Contact: expenses@codat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ValidTransactionTypes } from '../_speakeasy_enums';
import { mapValues } from '../../../runtime';
import { Decimal, toDecimal, fromDecimal } from '../../../runtime';
/**
 * 
 * @export
 * @interface TaxRateMappingInfo
 */
export interface TaxRateMappingInfo {
    [key: string]: any | any;
    /**
     * Unique identifier of tax rate.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    id?: string;
    /**
     * Name of the tax rate in the accounting software.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    name?: string;
    /**
     * Code for the tax rate from the accounting software.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    code?: string | null;
    /**
     * Effective tax rate.
     * @type {number}
     * @memberof TaxRateMappingInfo
     */
    effectiveTaxRate?: Decimal | number;
    /**
     * Total (not compounded) sum of the components of a tax rate.
     * @type {number}
     * @memberof TaxRateMappingInfo
     */
    totalTaxRate?: Decimal | number;
    /**
     * Supported transaction types for the account.
     * @type {Array<string>}
     * @memberof TaxRateMappingInfo
     */
    validTransactionTypes?: Array<ValidTransactionTypes>;
}


/**
 * @export
 */
export const TaxRateMappingInfoValidTransactionTypesEnum = {
    Payment: 'Payment',
    Refund: 'Refund',
    Reward: 'Reward',
    Chargeback: 'Chargeback'
} as const;
export type TaxRateMappingInfoValidTransactionTypesEnum = typeof TaxRateMappingInfoValidTransactionTypesEnum[keyof typeof TaxRateMappingInfoValidTransactionTypesEnum];


/**
 * Check if a given object implements the TaxRateMappingInfo interface.
 */
export function instanceOfTaxRateMappingInfo(value: object): value is TaxRateMappingInfo {
    return true;
}

export function TaxRateMappingInfoFromJSON(json: any): TaxRateMappingInfo {
    return TaxRateMappingInfoFromJSONTyped(json, false);
}

export function TaxRateMappingInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxRateMappingInfo {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'effectiveTaxRate': json['effectiveTaxRate'] == null ? undefined : toDecimal(json['effectiveTaxRate']),
        'totalTaxRate': json['totalTaxRate'] == null ? undefined : toDecimal(json['totalTaxRate']),
        'validTransactionTypes': json['validTransactionTypes'] == null ? undefined : json['validTransactionTypes'],
    };
}

export function TaxRateMappingInfoToJSON(json: any): TaxRateMappingInfo {
    return TaxRateMappingInfoToJSONTyped(json, false);
}

export function TaxRateMappingInfoToJSONTyped(value?: TaxRateMappingInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'id': value['id'],
        'name': value['name'],
        'code': value['code'],
        'effectiveTaxRate': fromDecimal(value['effectiveTaxRate']),
        'totalTaxRate': fromDecimal(value['totalTaxRate']),
        'validTransactionTypes': value['validTransactionTypes'],
    };
}


export interface GetMappingOptionsResponseTaxRateMappingInfo {
    [key: string]: any | any;
    /**
     * Unique identifier of tax rate.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    id?: string;
    /**
     * Name of the tax rate in the accounting software.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    name?: string;
    /**
     * Code for the tax rate from the accounting software.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    code?: string | null;
    /**
     * Effective tax rate.
     * @type {number}
     * @memberof TaxRateMappingInfo
     */
    effectiveTaxRate?: Decimal | number;
    /**
     * Total (not compounded) sum of the components of a tax rate.
     * @type {number}
     * @memberof TaxRateMappingInfo
     */
    totalTaxRate?: Decimal | number;
    /**
     * Supported transaction types for the account.
     * @type {Array<string>}
     * @memberof TaxRateMappingInfo
     */
    validTransactionTypes?: Array<TaxRateMappingInfoValidTransactionTypesEnum>;
}

export interface MappingOptionsGetResponseTaxRateMappingInfo {
    [key: string]: any | any;
    /**
     * Unique identifier of tax rate.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    id?: string;
    /**
     * Name of the tax rate in the accounting software.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    name?: string;
    /**
     * Code for the tax rate from the accounting software.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    code?: string | null;
    /**
     * Effective tax rate.
     * @type {number}
     * @memberof TaxRateMappingInfo
     */
    effectiveTaxRate?: Decimal | number;
    /**
     * Total (not compounded) sum of the components of a tax rate.
     * @type {number}
     * @memberof TaxRateMappingInfo
     */
    totalTaxRate?: Decimal | number;
    /**
     * Supported transaction types for the account.
     * @type {Array<string>}
     * @memberof TaxRateMappingInfo
     */
    validTransactionTypes?: Array<TaxRateMappingInfoValidTransactionTypesEnum>;
}

export interface MappingOptionsTaxRateMappingInfo {
    [key: string]: any | any;
    /**
     * Unique identifier of tax rate.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    id?: string;
    /**
     * Name of the tax rate in the accounting software.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    name?: string;
    /**
     * Code for the tax rate from the accounting software.
     * @type {string}
     * @memberof TaxRateMappingInfo
     */
    code?: string | null;
    /**
     * Effective tax rate.
     * @type {number}
     * @memberof TaxRateMappingInfo
     */
    effectiveTaxRate?: Decimal | number;
    /**
     * Total (not compounded) sum of the components of a tax rate.
     * @type {number}
     * @memberof TaxRateMappingInfo
     */
    totalTaxRate?: Decimal | number;
    /**
     * Supported transaction types for the account.
     * @type {Array<string>}
     * @memberof TaxRateMappingInfo
     */
    validTransactionTypes?: Array<TaxRateMappingInfoValidTransactionTypesEnum>;
}
