/* tslint:disable */
/* eslint-disable */
/**
 * Bill pay (synchronous solution)
 * The API reference for the synchronous Bill Pay solution.   The synchronous Bill Pay solution is an API and a set of supporting tools designed to integrate a bill pay flow into your app as quickly as possible. It\'s ideal for facilitating essential bill payment processes within your SMB\'s accounting software.  [Explore solution](https://docs.codat.io/payables/overview) | [See OpenAPI spec](https://github.com/codatio/oas)  --- ## Supported Integrations  | Integration                   | Supported | |-------------------------------|-----------| | FreeAgent                     | Yes       | | QuickBooks Online             | Yes       | | Oracle NetSuite               | Yes       | | Sage Intacct                  | Yes       | | Xero                          | Yes       | | Zoho Books                    | Yes       |  --- <!-- Start Codat Tags Table --> ## Endpoints  | Endpoints | Description | | :- |:- | | Companies | Create and manage your SMB users\' companies. | | Connections | Create new and manage existing data connections for a company. | | Company information | View company profile from the source platform. | | Bills | Get, create, and update Bills. | | Bill payments | Get, create, and update Bill payments. | | Suppliers | Get, create, and update Suppliers. | | Bank accounts | Create a bank account for a given company\'s connection. | <!-- End Codat Tags Table -->
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: support@codat.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../../../runtime';
/**
 * Reference to the supplier the record relates to.
 * @export
 * @interface SupplierRef
 */
export interface SupplierRef {
    /**
     * The supplier's unique ID
     * @type {string}
     * @memberof SupplierRef
     */
    id: string;
    /**
     * The supplier's name
     * @type {string}
     * @memberof SupplierRef
     */
    supplierName?: string | null;
}

/**
 * Check if a given object implements the SupplierRef interface.
 */
export function instanceOfSupplierRef(value: object): value is SupplierRef {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SupplierRefFromJSON(json: any): SupplierRef {
    return SupplierRefFromJSONTyped(json, false);
}

export function SupplierRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupplierRef {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        ...(json['supplierName'] !== undefined ? { 'supplierName': json['supplierName'] } : {}),
    };
}

export function SupplierRefToJSON(json: any): SupplierRef {
    return SupplierRefToJSONTyped(json, false);
}

export function SupplierRefToJSONTyped(value?: SupplierRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'supplierName': value['supplierName'],
    };
}


export interface BillCreateResponseSupplierRef {
    /**
     * The supplier's unique ID
     * @type {string}
     * @memberof SupplierRef
     */
    id: string;
    /**
     * The supplier's name
     * @type {string}
     * @memberof SupplierRef
     */
    supplierName?: string | null;
}

export interface BillEventWebhookSupplierRef {
    /**
     * The supplier's unique ID
     * @type {string}
     * @memberof SupplierRef
     */
    id: string;
    /**
     * The supplier's name
     * @type {string}
     * @memberof SupplierRef
     */
    supplierName?: string | null;
}

export interface BillSupplierRef {
    /**
     * The supplier's unique ID
     * @type {string}
     * @memberof SupplierRef
     */
    id: string;
    /**
     * The supplier's name
     * @type {string}
     * @memberof SupplierRef
     */
    supplierName?: string | null;
}

export interface BillUpdateResponseSupplierRef {
    /**
     * The supplier's unique ID
     * @type {string}
     * @memberof SupplierRef
     */
    id: string;
    /**
     * The supplier's name
     * @type {string}
     * @memberof SupplierRef
     */
    supplierName?: string | null;
}

export interface CreateBillResponseSupplierRef {
    /**
     * The supplier's unique ID
     * @type {string}
     * @memberof SupplierRef
     */
    id: string;
    /**
     * The supplier's name
     * @type {string}
     * @memberof SupplierRef
     */
    supplierName?: string | null;
}

export interface UpdateBillResponseSupplierRef {
    /**
     * The supplier's unique ID
     * @type {string}
     * @memberof SupplierRef
     */
    id: string;
    /**
     * The supplier's name
     * @type {string}
     * @memberof SupplierRef
     */
    supplierName?: string | null;
}
