/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Reference of the account to which the item is linked.
 */
export class CreateItemSourceModifiedDateBillItemAccountRef extends SpeakeasyBase {
  /**
   * 'id' from the Accounts data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * 'name' from the Accounts data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

/**
 * Reference of the tax rate to which the item is linked.
 */
export class CreateItemSourceModifiedDateBillItemTaxRateRef extends SpeakeasyBase {
  /**
   * Applicable tax rate.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "effectiveTaxRate" })
  effectiveTaxRate?: number;

  /**
   * 'id' from the 'taxRates' data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * 'name' from the 'taxRates' data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

/**
 * Item details that are only for bills.
 */
export class CreateItemSourceModifiedDateBillItem extends SpeakeasyBase {
  /**
   * Reference of the account to which the item is linked.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "accountRef" })
  @Type(() => CreateItemSourceModifiedDateBillItemAccountRef)
  accountRef?: CreateItemSourceModifiedDateBillItemAccountRef;

  /**
   * Short description of the product or service that has been bought by the customer.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * Reference of the tax rate to which the item is linked.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "taxRateRef" })
  @Type(() => CreateItemSourceModifiedDateBillItemTaxRateRef)
  taxRateRef?: CreateItemSourceModifiedDateBillItemTaxRateRef;

  /**
   * Unit price of the product or service.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "unitPrice" })
  unitPrice?: number;
}

/**
 * Reference of the account to which the item is linked.
 */
export class CreateItemSourceModifiedDateInvoiceItemAccountRef extends SpeakeasyBase {
  /**
   * 'id' from the Accounts data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * 'name' from the Accounts data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

/**
 * Reference of the tax rate to which the item is linked.
 */
export class CreateItemSourceModifiedDateInvoiceItemTaxRateRef extends SpeakeasyBase {
  /**
   * Applicable tax rate.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "effectiveTaxRate" })
  effectiveTaxRate?: number;

  /**
   * 'id' from the 'taxRates' data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * 'name' from the 'taxRates' data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

/**
 * Item details that are only for bills.
 */
export class CreateItemSourceModifiedDateInvoiceItem extends SpeakeasyBase {
  /**
   * Reference of the account to which the item is linked.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "accountRef" })
  @Type(() => CreateItemSourceModifiedDateInvoiceItemAccountRef)
  accountRef?: CreateItemSourceModifiedDateInvoiceItemAccountRef;

  /**
   * Short description of the product or service that has been bought by the customer.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * Reference of the tax rate to which the item is linked.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "taxRateRef" })
  @Type(() => CreateItemSourceModifiedDateInvoiceItemTaxRateRef)
  taxRateRef?: CreateItemSourceModifiedDateInvoiceItemTaxRateRef;

  /**
   * Unit price of the product or service.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "unitPrice" })
  unitPrice?: number;
}

/**
 * Current state of the item, either:
 *
 * @remarks
 *
 * - `Active`: Available for use
 * - `Archived`: Unavailable
 * - `Unknown`
 *
 * Due to a [limitation in Xero's API](https://docs.codat.io/integrations/accounting/xero/xero-faq#why-do-all-of-my-items-from-xero-have-their-status-as-unknown), all items from Xero are mapped as `Unknown`.
 */
export enum CreateItemSourceModifiedDateItemStatusEnum {
  Unknown = "Unknown",
  Active = "Active",
  Archived = "Archived",
}

export class CreateItemSourceModifiedDateMetadata extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "isDeleted" })
  isDeleted?: boolean;
}

/**
 * Type of the item.
 */
export enum CreateItemSourceModifiedDateTypeEnum {
  Unknown = "Unknown",
  Inventory = "Inventory",
  NonInventory = "NonInventory",
  Service = "Service",
}

/**
 * > View the coverage for items in the <a className="external" href="https://knowledge.codat.io/supported-features/accounting?view=tab-by-data-type&dataType=items" target="_blank">Data coverage explorer</a>.
 *
 * @remarks
 *
 * ## Overview
 *
 * **Items** allow your customers to save and track details of the products and services that they buy and sell.
 *
 */
export class CreateItemSourceModifiedDate extends SpeakeasyBase {
  /**
   * Item details that are only for bills.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "billItem" })
  @Type(() => CreateItemSourceModifiedDateBillItem)
  billItem?: CreateItemSourceModifiedDateBillItem;

  /**
   * Friendly reference for the item.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "code" })
  code?: string;

  /**
   * Identifier for the item that is unique to a company in the accounting platform.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Item details that are only for bills.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "invoiceItem" })
  @Type(() => CreateItemSourceModifiedDateInvoiceItem)
  invoiceItem?: CreateItemSourceModifiedDateInvoiceItem;

  /**
   * Whether you can use this item for bills.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "isBillItem" })
  isBillItem: boolean;

  /**
   * Whether you can use this item for invoices.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "isInvoiceItem" })
  isInvoiceItem: boolean;

  /**
   * Current state of the item, either:
   *
   * @remarks
   *
   * - `Active`: Available for use
   * - `Archived`: Unavailable
   * - `Unknown`
   *
   * Due to a [limitation in Xero's API](https://docs.codat.io/integrations/accounting/xero/xero-faq#why-do-all-of-my-items-from-xero-have-their-status-as-unknown), all items from Xero are mapped as `Unknown`.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "itemStatus" })
  itemStatus: CreateItemSourceModifiedDateItemStatusEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "metadata" })
  @Type(() => CreateItemSourceModifiedDateMetadata)
  metadata?: CreateItemSourceModifiedDateMetadata;

  /**
   * The date on which this record was last modified in Codat.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "modifiedDate" })
  modifiedDate?: string;

  /**
   * Name of the item in the accounting platform.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * The date on which this record was last modified in the originating system
   */
  @SpeakeasyMetadata()
  @Expose({ name: "sourceModifiedDate" })
  sourceModifiedDate?: string;

  /**
   * Type of the item.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: CreateItemSourceModifiedDateTypeEnum;
}

export class CreateItemRequest extends SpeakeasyBase {
  @SpeakeasyMetadata({ data: "request, media_type=application/json" })
  requestBody?: CreateItemSourceModifiedDate;

  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=companyId",
  })
  companyId: string;

  @SpeakeasyMetadata({
    data: "pathParam, style=simple;explode=false;name=connectionId",
  })
  connectionId: string;

  @SpeakeasyMetadata({
    data: "queryParam, style=form;explode=true;name=timeoutInMinutes",
  })
  timeoutInMinutes?: number;
}

export class CreateItem200ApplicationJSONChangesPushOperationRecordRef extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "dataType" })
  dataType?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;
}

export enum CreateItem200ApplicationJSONChangesTypeEnum {
  Unknown = "Unknown",
  Created = "Created",
  Modified = "Modified",
  Deleted = "Deleted",
  AttachmentUploaded = "AttachmentUploaded",
}

export class CreateItem200ApplicationJSONChanges extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "attachmentId" })
  attachmentId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "recordRef" })
  @Type(() => CreateItem200ApplicationJSONChangesPushOperationRecordRef)
  recordRef?: CreateItem200ApplicationJSONChangesPushOperationRecordRef;

  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type?: CreateItem200ApplicationJSONChangesTypeEnum;
}

/**
 * Reference of the account to which the item is linked.
 */
export class CreateItem200ApplicationJSONSourceModifiedDateBillItemAccountRef extends SpeakeasyBase {
  /**
   * 'id' from the Accounts data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * 'name' from the Accounts data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

/**
 * Reference of the tax rate to which the item is linked.
 */
export class CreateItem200ApplicationJSONSourceModifiedDateBillItemTaxRateRef extends SpeakeasyBase {
  /**
   * Applicable tax rate.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "effectiveTaxRate" })
  effectiveTaxRate?: number;

  /**
   * 'id' from the 'taxRates' data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * 'name' from the 'taxRates' data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

/**
 * Item details that are only for bills.
 */
export class CreateItem200ApplicationJSONSourceModifiedDateBillItem extends SpeakeasyBase {
  /**
   * Reference of the account to which the item is linked.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "accountRef" })
  @Type(() => CreateItem200ApplicationJSONSourceModifiedDateBillItemAccountRef)
  accountRef?: CreateItem200ApplicationJSONSourceModifiedDateBillItemAccountRef;

  /**
   * Short description of the product or service that has been bought by the customer.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * Reference of the tax rate to which the item is linked.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "taxRateRef" })
  @Type(() => CreateItem200ApplicationJSONSourceModifiedDateBillItemTaxRateRef)
  taxRateRef?: CreateItem200ApplicationJSONSourceModifiedDateBillItemTaxRateRef;

  /**
   * Unit price of the product or service.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "unitPrice" })
  unitPrice?: number;
}

/**
 * Reference of the account to which the item is linked.
 */
export class CreateItem200ApplicationJSONSourceModifiedDateInvoiceItemAccountRef extends SpeakeasyBase {
  /**
   * 'id' from the Accounts data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * 'name' from the Accounts data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

/**
 * Reference of the tax rate to which the item is linked.
 */
export class CreateItem200ApplicationJSONSourceModifiedDateInvoiceItemTaxRateRef extends SpeakeasyBase {
  /**
   * Applicable tax rate.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "effectiveTaxRate" })
  effectiveTaxRate?: number;

  /**
   * 'id' from the 'taxRates' data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * 'name' from the 'taxRates' data type.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;
}

/**
 * Item details that are only for bills.
 */
export class CreateItem200ApplicationJSONSourceModifiedDateInvoiceItem extends SpeakeasyBase {
  /**
   * Reference of the account to which the item is linked.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "accountRef" })
  @Type(
    () => CreateItem200ApplicationJSONSourceModifiedDateInvoiceItemAccountRef
  )
  accountRef?: CreateItem200ApplicationJSONSourceModifiedDateInvoiceItemAccountRef;

  /**
   * Short description of the product or service that has been bought by the customer.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "description" })
  description?: string;

  /**
   * Reference of the tax rate to which the item is linked.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "taxRateRef" })
  @Type(
    () => CreateItem200ApplicationJSONSourceModifiedDateInvoiceItemTaxRateRef
  )
  taxRateRef?: CreateItem200ApplicationJSONSourceModifiedDateInvoiceItemTaxRateRef;

  /**
   * Unit price of the product or service.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "unitPrice" })
  unitPrice?: number;
}

/**
 * Current state of the item, either:
 *
 * @remarks
 *
 * - `Active`: Available for use
 * - `Archived`: Unavailable
 * - `Unknown`
 *
 * Due to a [limitation in Xero's API](https://docs.codat.io/integrations/accounting/xero/xero-faq#why-do-all-of-my-items-from-xero-have-their-status-as-unknown), all items from Xero are mapped as `Unknown`.
 */
export enum CreateItem200ApplicationJSONSourceModifiedDateItemStatusEnum {
  Unknown = "Unknown",
  Active = "Active",
  Archived = "Archived",
}

export class CreateItem200ApplicationJSONSourceModifiedDateMetadata extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "isDeleted" })
  isDeleted?: boolean;
}

/**
 * Type of the item.
 */
export enum CreateItem200ApplicationJSONSourceModifiedDateTypeEnum {
  Unknown = "Unknown",
  Inventory = "Inventory",
  NonInventory = "NonInventory",
  Service = "Service",
}

/**
 * > View the coverage for items in the <a className="external" href="https://knowledge.codat.io/supported-features/accounting?view=tab-by-data-type&dataType=items" target="_blank">Data coverage explorer</a>.
 *
 * @remarks
 *
 * ## Overview
 *
 * **Items** allow your customers to save and track details of the products and services that they buy and sell.
 *
 */
export class CreateItem200ApplicationJSONSourceModifiedDate extends SpeakeasyBase {
  /**
   * Item details that are only for bills.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "billItem" })
  @Type(() => CreateItem200ApplicationJSONSourceModifiedDateBillItem)
  billItem?: CreateItem200ApplicationJSONSourceModifiedDateBillItem;

  /**
   * Friendly reference for the item.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "code" })
  code?: string;

  /**
   * Identifier for the item that is unique to a company in the accounting platform.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "id" })
  id?: string;

  /**
   * Item details that are only for bills.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "invoiceItem" })
  @Type(() => CreateItem200ApplicationJSONSourceModifiedDateInvoiceItem)
  invoiceItem?: CreateItem200ApplicationJSONSourceModifiedDateInvoiceItem;

  /**
   * Whether you can use this item for bills.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "isBillItem" })
  isBillItem: boolean;

  /**
   * Whether you can use this item for invoices.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "isInvoiceItem" })
  isInvoiceItem: boolean;

  /**
   * Current state of the item, either:
   *
   * @remarks
   *
   * - `Active`: Available for use
   * - `Archived`: Unavailable
   * - `Unknown`
   *
   * Due to a [limitation in Xero's API](https://docs.codat.io/integrations/accounting/xero/xero-faq#why-do-all-of-my-items-from-xero-have-their-status-as-unknown), all items from Xero are mapped as `Unknown`.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "itemStatus" })
  itemStatus: CreateItem200ApplicationJSONSourceModifiedDateItemStatusEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "metadata" })
  @Type(() => CreateItem200ApplicationJSONSourceModifiedDateMetadata)
  metadata?: CreateItem200ApplicationJSONSourceModifiedDateMetadata;

  /**
   * The date on which this record was last modified in Codat.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "modifiedDate" })
  modifiedDate?: string;

  /**
   * Name of the item in the accounting platform.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "name" })
  name?: string;

  /**
   * The date on which this record was last modified in the originating system
   */
  @SpeakeasyMetadata()
  @Expose({ name: "sourceModifiedDate" })
  sourceModifiedDate?: string;

  /**
   * Type of the item.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "type" })
  type: CreateItem200ApplicationJSONSourceModifiedDateTypeEnum;
}

/**
 * The status of the push operation.
 */
export enum CreateItem200ApplicationJSONStatusEnum {
  Pending = "Pending",
  Failed = "Failed",
  Success = "Success",
  TimedOut = "TimedOut",
}

export class CreateItem200ApplicationJSONValidationValidationItem extends SpeakeasyBase {
  @SpeakeasyMetadata()
  @Expose({ name: "itemId" })
  itemId?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "message" })
  message?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "validatorName" })
  validatorName?: string;
}

/**
 * A human-readable object describing validation decisions Codat has made when pushing data into the platform. If a push has failed because of validation errors, they will be detailed here.
 */
export class CreateItem200ApplicationJSONValidation extends SpeakeasyBase {
  @SpeakeasyMetadata({
    elemType: CreateItem200ApplicationJSONValidationValidationItem,
  })
  @Expose({ name: "errors" })
  @Type(() => CreateItem200ApplicationJSONValidationValidationItem)
  errors?: CreateItem200ApplicationJSONValidationValidationItem[];

  @SpeakeasyMetadata({
    elemType: CreateItem200ApplicationJSONValidationValidationItem,
  })
  @Expose({ name: "warnings" })
  @Type(() => CreateItem200ApplicationJSONValidationValidationItem)
  warnings?: CreateItem200ApplicationJSONValidationValidationItem[];
}

/**
 * Success
 */
export class CreateItem200ApplicationJSON extends SpeakeasyBase {
  @SpeakeasyMetadata({ elemType: CreateItem200ApplicationJSONChanges })
  @Expose({ name: "changes" })
  @Type(() => CreateItem200ApplicationJSONChanges)
  changes?: CreateItem200ApplicationJSONChanges[];

  /**
   * Unique identifier for your SMB in Codat.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "companyId" })
  companyId: string;

  /**
   * The datetime when the push was completed, null if Pending.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "completedOnUtc" })
  completedOnUtc?: string;

  /**
   * > View the coverage for items in the <a className="external" href="https://knowledge.codat.io/supported-features/accounting?view=tab-by-data-type&dataType=items" target="_blank">Data coverage explorer</a>.
   *
   * @remarks
   *
   * ## Overview
   *
   * **Items** allow your customers to save and track details of the products and services that they buy and sell.
   *
   */
  @SpeakeasyMetadata()
  @Expose({ name: "data" })
  @Type(() => CreateItem200ApplicationJSONSourceModifiedDate)
  data?: CreateItem200ApplicationJSONSourceModifiedDate;

  /**
   * Unique identifier for a company's data connection.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "dataConnectionKey" })
  dataConnectionKey: string;

  /**
   * The type of data being pushed, eg invoices, customers.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "dataType" })
  dataType?: string;

  @SpeakeasyMetadata()
  @Expose({ name: "errorMessage" })
  errorMessage?: string;

  /**
   * A unique identifier generated by Codat to represent this single push operation. This identifier can be used to track the status of the push, and should be persisted.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "pushOperationKey" })
  pushOperationKey: string;

  /**
   * The datetime when the push was requested.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "requestedOnUtc" })
  requestedOnUtc: string;

  /**
   * The status of the push operation.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "status" })
  status: CreateItem200ApplicationJSONStatusEnum;

  @SpeakeasyMetadata()
  @Expose({ name: "statusCode" })
  statusCode: number;

  @SpeakeasyMetadata()
  @Expose({ name: "timeoutInMinutes" })
  timeoutInMinutes?: number;

  @SpeakeasyMetadata()
  @Expose({ name: "timeoutInSeconds" })
  timeoutInSeconds?: number;

  /**
   * A human-readable object describing validation decisions Codat has made when pushing data into the platform. If a push has failed because of validation errors, they will be detailed here.
   */
  @SpeakeasyMetadata()
  @Expose({ name: "validation" })
  @Type(() => CreateItem200ApplicationJSONValidation)
  validation?: CreateItem200ApplicationJSONValidation;
}

export class CreateItemResponse extends SpeakeasyBase {
  @SpeakeasyMetadata()
  contentType: string;

  @SpeakeasyMetadata()
  statusCode: number;

  @SpeakeasyMetadata()
  rawResponse?: AxiosResponse;

  /**
   * Success
   */
  @SpeakeasyMetadata()
  createItem200ApplicationJSONObject?: CreateItem200ApplicationJSON;
}
