workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    accounting-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Accounting.yaml
    assess-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Assess.yaml
    bank-feeds-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Bank-Feeds.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/bank-feeds-source
    banking-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Banking.yaml
    commerce-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Commerce.yaml
    common-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Platform.yaml
    files-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Files.yaml
    lending-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Lending.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/lending-source
    platform-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Platform.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/platform-source
    sync-for-commerce-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Commerce.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-commerce-source
    sync-for-commerce-version-1-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Commerce-v1.yaml
    sync-for-expenses-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Expenses.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-expenses-source
    sync-for-expenses-version-1-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Expenses-v1.yaml
    sync-for-payables-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Payables.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-payables-source
    sync-for-payables-version-1-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Payables-v1.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-payables-version-1-source
    sync-for-payroll-source:
        inputs:
            - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Payroll.yaml
        registry:
            location: registry.speakeasyapi.dev/codat/codat/sync-for-payroll-source
targets:
    accounting-library:
        target: typescript
        source: accounting-source
        output: previous-versions/accounting
        publish:
            npm:
                token: $npm_token
    assess-library:
        target: typescript
        source: assess-source
        output: previous-versions/assess
        publish:
            npm:
                token: $npm_token
    bank-feeds-library:
        target: typescript
        source: bank-feeds-source
        output: bank-feeds
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/bank-feeds-source-typescript-code-samples
            blocking: false
    banking-library:
        target: typescript
        source: banking-source
        output: previous-versions/banking
        publish:
            npm:
                token: $npm_token
    commerce-library:
        target: typescript
        source: commerce-source
        output: previous-versions/commerce
        publish:
            npm:
                token: $npm_token
    common-library:
        target: typescript
        source: common-source
        output: previous-versions/common
        publish:
            npm:
                token: $npm_token
    files-library:
        target: typescript
        source: files-source
        output: previous-versions/files
        publish:
            npm:
                token: $npm_token
    lending-library:
        target: typescript
        source: lending-source
        output: lending
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/lending-source-typescript-code-samples
            blocking: false
    platform-library:
        target: typescript
        source: platform-source
        output: platform
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/platform-source-typescript-code-samples
            blocking: false
    sync-for-commerce-library:
        target: typescript
        source: sync-for-commerce-source
        output: sync-for-commerce
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-commerce-source-typescript-code-samples
            blocking: false
    sync-for-commerce-version-1-library:
        target: typescript
        source: sync-for-commerce-version-1-source
        output: previous-versions/sync-for-commerce-version-1
        publish:
            npm:
                token: $npm_token
    sync-for-expenses-library:
        target: typescript
        source: sync-for-expenses-source
        output: sync-for-expenses
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-expenses-source-typescript-code-samples
            blocking: false
    sync-for-expenses-version-1-library:
        target: typescript
        source: sync-for-expenses-version-1-source
        output: previous-versions/sync-for-expenses-version-1
        publish:
            npm:
                token: $npm_token
    sync-for-payables-library:
        target: typescript
        source: sync-for-payables-source
        output: sync-for-payables
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-payables-source-typescript-code-samples
            blocking: false
    sync-for-payables-version-1-library:
        target: typescript
        source: sync-for-payables-version-1-source
        output: previous-versions/sync-for-payables-version-1
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-payables-version-1-source-typescript-code-samples
            blocking: false
    sync-for-payroll-library:
        target: typescript
        source: sync-for-payroll-source
        output: sync-for-payroll
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/codat/codat/sync-for-payroll-source-typescript-code-samples
            blocking: false
