workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
  accounting-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Accounting.yaml
  assess-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Assess.yaml
  bank-feeds-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Bank-Feeds.yaml
  banking-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Banking.yaml
  commerce-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Commerce.yaml
  common-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Platform.yaml
  files-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Files.yaml
  lending-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Lending.yaml
  platform-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Platform.yaml
    registry:
      location: registry.speakeasyapi.dev/codat/codat/platform-source
  sync-for-commerce-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Commerce.yaml
  sync-for-commerce-version-1-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Commerce-v1.yaml
  sync-for-expenses-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Expenses.yaml
  sync-for-expenses-version-1-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Expenses-v1.yaml
  sync-for-payables-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Payables.yaml
  sync-for-payables-version-1-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Payables-v1.yaml
  sync-for-payroll-source:
    inputs:
    - location: https://raw.githubusercontent.com/codatio/oas/main/yaml/Codat-Sync-Payroll.yaml
targets:
  accounting-library:
    target: typescript
    source: accounting-source
    output: previous-versions/accounting
    publish:
      npm: !!set
        $npm_token: null
  assess-library:
    target: typescript
    source: assess-source
    output: previous-versions/assess
    publish:
      npm: !!set
        $npm_token: null
  bank-feeds-library:
    target: typescript
    source: bank-feeds-source
    output: bank-feeds
    publish:
      npm: !!set
        $npm_token: null
  banking-library:
    target: typescript
    source: banking-source
    output: previous-versions/banking
    publish:
      npm: !!set
        $npm_token: null
  commerce-library:
    target: typescript
    source: commerce-source
    output: previous-versions/commerce
    publish:
      npm: !!set
        $npm_token: null
  common-library:
    target: typescript
    source: common-source
    output: previous-versions/common
    publish:
      npm: !!set
        $npm_token: null
  files-library:
    target: typescript
    source: files-source
    output: previous-versions/files
    publish:
      npm: !!set
        $npm_token: null
  lending-library:
    target: typescript
    source: lending-source
    output: lending
    publish:
      npm: !!set
        $npm_token: null
  platform-library:
    target: typescript
    source: platform-source
    output: platform
    publish:
      npm: !!set
        $npm_token: null
  sync-for-commerce-library:
    target: typescript
    source: sync-for-commerce-source
    output: sync-for-commerce
    publish:
      npm: !!set
        $npm_token: null
  sync-for-commerce-version-1-library:
    target: typescript
    source: sync-for-commerce-version-1-source
    output: previous-versions/sync-for-commerce-version-1
    publish:
      npm: !!set
        $npm_token: null
  sync-for-expenses-library:
    target: typescript
    source: sync-for-expenses-source
    output: sync-for-expenses
    publish:
      npm: !!set
        $npm_token: null
  sync-for-expenses-version-1-library:
    target: typescript
    source: sync-for-expenses-version-1-source
    output: previous-versions/sync-for-expenses-version-1
    publish:
      npm: !!set
        $npm_token: null
  sync-for-payables-library:
    target: typescript
    source: sync-for-payables-source
    output: sync-for-payables
    publish:
      npm: !!set
        $npm_token: null
  sync-for-payables-version-1-library:
    target: typescript
    source: sync-for-payables-version-1-source
    output: previous-versions/sync-for-payables-version-1
    publish:
      npm: !!set
        $npm_token: null
  sync-for-payroll-library:
    target: typescript
    source: sync-for-payroll-source
    output: sync-for-payroll
    publish:
      npm: !!set
        $npm_token: null
