/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { billPaymentsCreate } from "../funcs/billPaymentsCreate.js";
import { billPaymentsGetPaymentOptions } from "../funcs/billPaymentsGetPaymentOptions.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "./models/operations/index.js";
import * as shared from "./models/shared/index.js";
import { unwrapAsync } from "./types/fp.js";

export class BillPayments extends ClientSDK {
  /**
   * Get payment mapping options
   *
   * @remarks
   * Use the *Get mapping options - Payments* endpoint to return a list of available mapping options for a given company's connection ID.
   *
   * By default, this endpoint returns a list of active bank accounts. You can use [querying](https://docs.codat.io/using-the-api/querying) to change that.
   *
   * Mapping options are a set of bank accounts used to configure the SMB's payables integration.
   */
  async getPaymentOptions(
    request: operations.GetMappingOptionsPaymentsRequest,
    options?: RequestOptions,
  ): Promise<shared.PaymentMappingOptions> {
    return unwrapAsync(billPaymentsGetPaymentOptions(
      this,
      request,
      options,
    ));
  }

  /**
   * Create bill payment
   *
   * @remarks
   * The *Create bill payment* endpoint creates a new [bill payment](https://docs.codat.io/sync-for-payables-api#/schemas/BillPayment) for a given company's connection.
   *
   * [Bill payments](https://docs.codat.io/sync-for-payables-api#/schemas/BillPayment) are an allocation of money within any Accounts Payable account.
   */
  async create(
    request: operations.CreateBillPaymentRequest,
    options?: RequestOptions,
  ): Promise<shared.BillPayment> {
    return unwrapAsync(billPaymentsCreate(
      this,
      request,
      options,
    ));
  }
}
