/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";

export type GetLastSuccessfulSyncRequest = {
  /**
   * Unique identifier for a company.
   */
  companyId: string;
};

/** @internal */
export type GetLastSuccessfulSyncRequest$Outbound = {
  companyId: string;
};

/** @internal */
export const GetLastSuccessfulSyncRequest$outboundSchema: z.ZodType<
  GetLastSuccessfulSyncRequest$Outbound,
  z.ZodTypeDef,
  GetLastSuccessfulSyncRequest
> = z.object({
  companyId: z.string(),
});

export function getLastSuccessfulSyncRequestToJSON(
  getLastSuccessfulSyncRequest: GetLastSuccessfulSyncRequest,
): string {
  return JSON.stringify(
    GetLastSuccessfulSyncRequest$outboundSchema.parse(
      getLastSuccessfulSyncRequest,
    ),
  );
}
