/* tslint:disable */
/* eslint-disable */
export * from './Account';
export * from './shared/accountmappinginfo';
export * from './shared/accountprototype';
export * from './shared/accountreference';
export * from './AccountReference1';
export * from './shared/accountstatus';
export * from './shared/accounttype';
export * from './shared/accountingaddress';
export * from './shared/accountingaddresstype';
export * from './shared/adjustmenttransactionline';
export * from './shared/adjustmenttransactionrequest';
export * from './shared/adjustmenttransactionresponse';
export * from './shared/apaccountref';
export * from './shared/attachment';
export * from './shared/bankaccount';
export * from './shared/bankaccountdetails';
export * from './BankAccountPrototype';
export * from './shared/bankaccountreference';
export * from './shared/bankaccountstatus';
export * from './shared/clientratelimitwebhook';
export * from './shared/clientratelimitwebhookpayload';
export * from './shared/companies';
export * from './shared/company';
export * from './shared/companyconfiguration';
export * from './CompanyDetails';
export * from './shared/companyinformation';
export * from './shared/companyreference';
export * from './shared/companyreferencelinks';
export * from './shared/companyrequestbody';
export * from './shared/companysyncstatus';
export * from './shared/companyupdaterequest';
export * from './shared/connection';
export * from './shared/connections';
export * from './shared/contact';
export * from './shared/createaccountresponse';
export * from './CreateAccountResponseAllOfData';
export * from './shared/createbankaccountresponse';
export * from './CreateBankAccountResponseAllOfData';
export * from './operations/createconnectionrequestbody';
export * from './shared/createcustomerresponse';
export * from './CreateCustomerResponseAllOfData';
export * from './shared/createexpenseresponse';
export * from './shared/createreimbursableexpenseresponse';
export * from './shared/createsupplierresponse';
export * from './CreateSupplierResponseAllOfData';
export * from './shared/customer';
export * from './shared/customerdetails';
export * from './shared/customerstatus';
export * from './shared/customers';
export * from './shared/dataconnectionerror';
export * from './shared/dataconnectionstatus';
export * from './shared/datastatus';
export * from './DataStatuses';
export * from './shared/datatype';
export * from './shared/definitiontransaction';
export * from './ErrorMessage';
export * from './shared/errorvalidation';
export * from './shared/errorvalidationitem';
export * from './shared/expensecontactref';
export * from './shared/expensetransaction';
export * from './shared/expensetransactionline';
export * from './shared/expensessyncwebhook';
export * from './shared/expensessyncwebhookpayload';
export * from './shared/halref';
export * from './shared/integrationtype';
export * from './shared/invoiceto';
export * from './shared/itemref';
export * from './shared/items';
export * from './shared/links';
export * from './shared/mappingoptions';
export * from './shared/metadata';
export * from './Model3';
export * from './PagingInfo';
export * from './shared/phonenumberitems';
export * from './shared/pulloperation';
export * from './shared/pulloperations';
export * from './shared/pushchangetype';
export * from './shared/pushfieldvalidation';
export * from './shared/pushoperation';
export * from './shared/pushoperationchange';
export * from './shared/pushoperationref';
export * from './shared/pushoperationstatus';
export * from './shared/pushoperations';
export * from './shared/pushoption';
export * from './shared/pushoptionchoice';
export * from './shared/pushoptionproperty';
export * from './shared/pushoptiontype';
export * from './shared/pushvalidationinfo';
export * from './shared/recordref';
export * from './shared/reimbursableexpensetransaction';
export * from './shared/reimbursableexpensetransactionline';
export * from './shared/reimbursementcontactref';
export * from './shared/status';
export * from './shared/supplementaldata';
export * from './shared/supplier';
export * from './shared/supplierdetails';
export * from './shared/supplierstatus';
export * from './shared/suppliers';
export * from './SyncCompleteWebhook';
export * from './SyncCompleteWebhookData';
export * from './SyncFailedWebhook';
export * from './SyncFailedWebhookData';
export * from './SyncInitiated';
export * from './shared/taxratemappinginfo';
export * from './shared/trackingcategorymappinginfo';
export * from './shared/trackingref';
export * from './shared/trackingrefadjustmenttransaction';
export * from './shared/transaction';
export * from './shared/transactionstatus';
export * from './shared/transactions';
export * from './shared/transfertransactionrequest';
export * from './TransferTransactionRequestFrom';
export * from './TransferTransactionRequestTo';
export * from './shared/transfertransactionresponse';
export * from './UpdateConnection';
export * from './shared/updatecustomerresponse';
export * from './UpdateCustomerResponseAllOfData';
export * from './shared/updateexpenserequest';
export * from './shared/updateexpenseresponse';
export * from './UpdateReimbursableExpenseTransactionRequest';
export * from './shared/updatesupplierresponse';
export * from './UpdateSupplierResponseAllOfData';
export * from './shared/validdatatypelinks';
export * from './shared/validation';
export * from './shared/validationitem';
export * from './shared/weblink';
export * from './shared/codatfile';
export * from './shared/attachmentupload';
export * from './_speakeasy_enums';
export * from './_speakeasy_hoisted';
export type { Security } from '../../lib/sdkconfig';

export type { ListCompaniesRequest } from './operations/listcompanies';
export type { GetCompanyRequest } from './operations/getcompany';
export type { ReplaceCompanyRequest } from './operations/replacecompany';
export type { UpdateCompanyRequest } from './operations/updatecompany';
export type { DeleteCompanyRequest } from './operations/deletecompany';
export type { ListConnectionsRequest } from './operations/listconnections';
export type { CreateConnectionRequest } from './operations/createconnection';
export type { GetConnectionRequest } from './operations/getconnection';
export type { UnlinkConnectionRequest } from './operations/unlinkconnection';
export type { DeleteConnectionRequest } from './operations/deleteconnection';
export type { CreatePartnerExpenseConnectionRequest } from './operations/createpartnerexpenseconnection';
export type { GetCompanyInfoRequest } from './operations/getcompanyinfo';
export type { GetCompanyConfigurationRequest } from './operations/getcompanyconfiguration';
export type { SetCompanyConfigurationRequest } from './operations/setcompanyconfiguration';
export type { GetMappingOptionsRequest } from './operations/getmappingoptions';
export type { GetLastSuccessfulSyncRequest } from './operations/getlastsuccessfulsync';
export type { GetLatestSyncRequest } from './operations/getlatestsync';
export type { ListSyncsRequest } from './operations/listsyncs';
export type { GetSyncByIdRequest } from './operations/getsyncbyid';
export type { ListSyncTransactionsRequest } from './operations/listsynctransactions';
export type { GetSyncTransactionRequest } from './operations/getsynctransaction';
export type { CreateExpenseTransactionRequest } from './operations/createexpensetransaction';
export type { UpdateExpenseTransactionRequest } from './operations/updateexpensetransaction';
export type { CreateTransferTransactionRequest } from './operations/createtransfertransaction';
export type { CreateAdjustmentTransactionRequest } from './operations/createadjustmenttransaction';
export type { CreateReimbursableExpenseTransactionRequest } from './operations/createreimbursableexpensetransaction';
export type { UploadExpenseAttachmentRequest } from './operations/uploadexpenseattachment';
export type { RefreshAllDataTypesRequest } from './operations/refreshalldatatypes';
export type { GetDataStatusRequest } from './operations/getdatastatus';
export type { RefreshDataTypeRequest } from './operations/refreshdatatype';
export type { ListPullOperationsRequest } from './operations/listpulloperations';
export type { GetPullOperationRequest } from './operations/getpulloperation';
export type { ListPushOperationsRequest } from './operations/listpushoperations';
export type { GetPushOperationRequest } from './operations/getpushoperation';
export type { CreateAccountRequest } from './operations/createaccount';
export type { GetCreateChartOfAccountsModelRequest } from './operations/getcreatechartofaccountsmodel';
export type { CreateBankAccountRequest } from './operations/createbankaccount';
export type { GetCreateBankAccountsModelRequest } from './operations/getcreatebankaccountsmodel';
export type { ListCustomersRequest } from './operations/listcustomers';
export type { GetCustomerRequest } from './operations/getcustomer';
export type { CreateCustomerRequest } from './operations/createcustomer';
export type { UpdateCustomerRequest } from './operations/updatecustomer';
export type { ListSuppliersRequest } from './operations/listsuppliers';
export type { GetSupplierRequest } from './operations/getsupplier';
export type { CreateSupplierRequest } from './operations/createsupplier';
export type { UpdateSupplierRequest } from './operations/updatesupplier';

export * as operations from './operations';
export * as shared from './shared';
