/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

/**
 * Status of the transaction.
 */
export enum TransactionStatus {
  Unknown = "Unknown",
  Pending = "Pending",
  ValidationError = "ValidationError",
  Completed = "Completed",
  PushError = "PushError",
}
