name: Release Accounting library
'on':
  push:
    paths:
    - accounting/RELEASES.md
    branches:
    - main
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v14
    with:
      create_release: true
      publish_typescript: true
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      npm_token: ${{ secrets.NPM_TOKEN }}
