name: Generate Sync for Payables version 1 library
'on':
  workflow_dispatch:
    inputs:
      force:
        description: Force generation of SDKs
        type: boolean
        default: false
      set_version:
        description: Optionally set a specific SDK version.
        type: string
jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      mode: pr
      speakeasy_version: latest
      force: ${{ github.event.inputs.force }}
      set_version: ${{ github.event.inputs.set_version }}
      target: sync-for-payables-version-1-library
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
      npm_token: ${{ secrets.NPM_TOKEN }}
